#![Spark Logo](http://spark-mooc.github.io/web-assets/images/ta_Spark-logo-small.png) + ![Python Logo](http://spark-mooc.github.io/web-assets/images/python-logo-master-v3-TM-flattened_small.png)
#Power Plant Machine Learning Pipeline Application
This notebook is an end-to-end exercise of performing Extract-Transform-Load and Exploratory Data Analysis on a real-world dataset, and then applying several different machine learning algorithms to solve a supervised regression problem on the dataset.

** This notebook covers: **
* *Part 1: Business Understanding*
* *Part 2: Load Your Data*
* *Part 3: Explore Your Data*
* *Part 4: Visualize Your Data*
* *Part 5: Data Preparation*
* *Part 6: Data Modeling*
* *Part 7: Tuning and Evaluation*

*Our goal is to accurately predict power output given a set of environmental readings from various sensors in a natural gas-fired power generation plant.*

** Background **

Power generation is a complex process, and understanding and predicting power output is an important element in managing a plant and its connection to the power grid. The operators of a regional power grid create predictions of power demand based on historical information and environmental factors (e.g., temperature). They then compare the predictions against available resources (e.g., coal, natural gas, nuclear, solar, wind, hydro power plants). Power generation technologies such as solar and wind are highly dependent on environmental conditions, and all generation technologies are subject to planned and unplanned maintenance.

Here is an real-world example of predicted demand (on two time scales), actual demand, and available resources from the California power grid: http://www.caiso.com/Pages/TodaysOutlook.aspx

![](http://content.caiso.com/outlook/SP/ems_small.gif)

The challenge for a power grid operator is how to handle a shortfall in available resources versus actual demand. There are three solutions to  a power shortfall: build more base load power plants (this process can take many years to decades of planning and construction), buy and import power from other regional power grids (this choice can be very expensive and is limited by the power transmission interconnects between grids and the excess power available from other grids), or turn on small [Peaker or Peaking Power Plants](https://en.wikipedia.org/wiki/Peaking_power_plant). Because grid operators need to respond quickly to a power shortfall to avoid a power outage, grid operators rely on a combination of the last two choices. In this exercise, we'll focus on the last choice.

** The Business Problem **

Because they supply power only occasionally, the power supplied by a peaker power plant commands a much higher price per kilowatt hour than power from a power grid's base power plants. A peaker plant may operate many hours a day, or it may operate only a few hours per year, depending on the condition of the region's electrical grid. Because of the cost of building an efficient power plant, if a peaker plant is only going to be run for a short or highly variable time it does not make economic sense to make it as efficient as a base load power plant. In addition, the equipment and fuels used in base load plants are often unsuitable for use in peaker plants because the fluctuating conditions would severely strain the equipment.

The power output of a peaker power plant varies depending on environmental conditions, so the business problem is _predicting the power output of a peaker power plant as a function of the environmental conditions_ -- since this would enable the grid operator to make economic tradeoffs about the number of peaker plants to turn on (or whether to buy expensive power from another grid).

Given this business problem, we need to first perform Exploratory Data Analysis to understand the data and then translate the business problem (predicting power output as a function of envionmental conditions) into a Machine Learning task.  In this instance, the ML task is regression since the label (or target) we are trying to predict is numeric. We will use an [Apache Spark ML Pipeline](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark-ml-package) to perform the regression.

The real-world data we are using in this notebook consists of 9,568 data points, each with 4 environmental attributes collected from a Combined Cycle Power Plant over 6 years (2006-2011), and is provided by the University of California, Irvine at [UCI Machine Learning Repository Combined Cycle Power Plant Data Set](https://archive.ics.uci.edu/ml/datasets/Combined+Cycle+Power+Plant). You can find more details about the dataset on the UCI page, including the following background publications:
* Pinar Tüfekci, [Prediction of full load electrical power output of a base load operated combined cycle power plant using machine learning methods](http://www.journals.elsevier.com/international-journal-of-electrical-power-and-energy-systems/), International Journal of Electrical Power & Energy Systems, Volume 60, September 2014, Pages 126-140, ISSN 0142-0615.
* Heysem Kaya, Pinar Tüfekci and Fikret S. Gürgen: [Local and Global Learning Methods for Predicting Power of a Combined Gas & Steam Turbine](http://psrcentre.org/images/extraimages/70.%20312595.pdf), Proceedings of the International Conference on Emerging Trends in Computer and Electronics Engineering ICETCEE 2012, pp. 13-18 (Mar. 2012, Dubai).

**TODO**: Read the documentation and examples for [Spark Machine Learning Pipeline](https://spark.apache.org/docs/1.6.2/ml-guide.html#main-concepts-in-pipelines).

## Part 1: Business Understanding
The first step in any machine learning task is to understand the business need.

As described in the overview we are trying to predict power output given a set of readings from various sensors in a gas-fired power generation plant.

The problem is a regression problem since the label (or target) we are trying to predict is numeric.

## Part 2: Extract-Transform-Load (ETL) Your Data

Now that we understand what we are trying to do, the first step is to load our data into a format we can query and use.  This is known as ETL or "Extract-Transform-Load".  We will load our file from Amazon S3.

Note: Alternatively we could upload our data using "Databricks Menu > Tables > Create Table", assuming we had the raw files on our local computer.

Our data is available on Amazon s3 at the following path:

`dbfs:/databricks-datasets/power-plant/data`


**TODO**: Let's start by printing a sample of the data.

We'll use the built-in Databricks functions for exploring the Databricks filesystem (DBFS)

Use `display(dbutils.fs.ls("/databricks-datasets/power-plant/data"))` to list the files in the directory

In [0]:
display(dbutils.fs.ls("/databricks-datasets/power-plant/data"))

path name size dbfs:/databricks-datasets/power-plant/data/Sheet1.tsv Sheet1.tsv 308693 dbfs:/databricks-datasets/power-plant/data/Sheet2.tsv Sheet2.tsv 308693 dbfs:/databricks-datasets/power-plant/data/Sheet3.tsv Sheet3.tsv 308693 dbfs:/databricks-datasets/power-plant/data/Sheet4.tsv Sheet4.tsv 308693 dbfs:/databricks-datasets/power-plant/data/Sheet5.tsv Sheet5.tsv 308693

Next, use the `dbutils.fs.head` command to look at the first 65,536 bytes of the first file in the directory.

Use `print(dbutils.fs.head("/databricks-datasets/power-plant/data/Sheet1.tsv"))` to list the files in the directory

In [0]:
print(dbutils.fs.head("/databricks-datasets/power-plant/data/Sheet1.tsv"))

[Truncated to first 65536 bytes]
AT	V	AP	RH	PE
14.96	41.76	1024.07	73.17	463.26
25.18	62.96	1020.04	59.08	444.37
5.11	39.4	1012.16	92.14	488.56
20.86	57.32	1010.24	76.64	446.48
10.82	37.5	1009.23	96.62	473.9
26.27	59.44	1012.23	58.77	443.67
15.89	43.96	1014.02	75.24	467.35
9.48	44.71	1019.12	66.43	478.42
14.64	45	1021.78	41.25	475.98
11.74	43.56	1015.14	70.72	477.5
17.99	43.72	1008.64	75.04	453.02
20.14	46.93	1014.66	64.22	453.99
24.34	73.5	1011.31	84.15	440.29
25.71	58.59	1012.77	61.83	451.28
26.19	69.34	1009.48	87.59	433.99
21.42	43.79	1015.76	43.08	462.19
18.21	45	1022.86	48.84	467.54
11.04	41.74	1022.6	77.51	477.2
14.45	52.75	1023.97	63.59	459.85
13.97	38.47	1015.15	55.28	464.3
17.76	42.42	1009.09	66.26	468.27
5.41	40.07	1019.16	64.77	495.24
7.76	42.28	1008.52	83.31	483.8
27.23	63.9	1014.3	47.19	443.61
27.36	48.6	1003.18	54.93	436.06
27.47	70.72	1009.97	74.62	443.25
14.6	39.31	1011.11	72.52	464.16
7.91	39.96	1023.57	88.44	475.52
5.81	35.79	1012.14	92.28	484.41
30.53	65.18	1012.69	4

`dbutils.fs` has its own help facility, which we can use to see the various available functions.

In [0]:
dbutils.fs.help()

dbutils.fs provides utilities for working with FileSystems. Most methods in
this package can take either a DBFS path (e.g., "/foo" or "dbfs:/foo"), or
another FileSystem URI.

For more info about a method, use dbutils.fs.help("methodName") .

In notebooks, you can also use the %fs shorthand to access DBFS. The %fs shorthand maps
straightforwardly onto dbutils calls. For example, "%fs head --maxBytes=10000 /file/path"
translates into "dbutils.fs.head("/file/path", maxBytes = 10000)".
 fsutils cp(from: String, to: String, recurse: boolean = false): boolean -> Copies a file or directory, possibly across FileSystems head(file: String, maxBytes: int = 65536): String -> Returns up to the first 'maxBytes' bytes of the given file as a String encoded in UTF-8 ls(dir: String): Seq -> Lists the contents of a directory mkdirs(dir: String): boolean -> Creates the given directory if it does not exist, also creating any necessary parent directories mv(from: String, to: String, recurse: boolean = false): boolean -> Moves a file or directory, possibly across FileSystems put(file: String, contents: String, overwrite: boolean = false): boolean -> Writes the given String out to a file, encoded in UTF-8 rm(dir: String, recurse: boolean = false): boolean -> Removes a file or directory mount mount(source: String, mountPoint: String, encryptionType: String = "", owner: String = null, extraConfigs: Map = Map.empty[String, String]): boolean -> Mounts the given source directory into DBFS at the given mount point mounts: Seq -> Displays information about what is mounted within DBFS refreshMounts: boolean -> Forces all machines in this cluster to refresh their mount cache, ensuring they receive the most recent information unmount(mountPoint: String): boolean -> Deletes a DBFS mount point

### Exercise 2(a)

Now, let's use PySpark instead to print the first 5 lines of the data.

*Hint*: First create an RDD from the data by using [`sc.textFile("dbfs:/databricks-datasets/power-plant/data")`](https://spark.apache.org/docs/1.6.2/api/python/pyspark.html#pyspark.SparkContext.textFile) to read the data into an RDD.

*Hint*: Then figure out how to use the RDD [`take()`](https://spark.apache.org/docs/1.6.2/api/python/pyspark.html#pyspark.RDD.take) method to extract the first 5 lines of the RDD and print each line.

In [0]:
# TODO: Load the data and print the first five lines.
textRDD = sc.textFile("dbfs:/databricks-datasets/power-plant/data") 

for line in textRDD.take(5):
  print(line)

AT	V	AP	RH	PE
14.96	41.76	1024.07	73.17	463.26
25.18	62.96	1020.04	59.08	444.37
5.11	39.4	1012.16	92.14	488.56
20.86	57.32	1010.24	76.64	446.48


From our initial exploration of a sample of the data, we can make several observations for the ETL process:
  - The data is a set of .tsv (Tab Seperated Values) files (i.e., each row of the data is separated using tabs)
  - There is a header row, which is the name of the columns
  - It looks like the type of the data in each column is consistent (i.e., each column is of type double)

Our schema definition from UCI appears below:
- AT = Atmospheric Temperature in C
- V = Exhaust Vacuum Speed
- AP = Atmospheric Pressure
- RH = Relative Humidity
- PE = Power Output.  This is the value we are trying to predict given the measurements above.

We are ready to create a DataFrame from the TSV data. Spark does not have a native method for performing this operation, however we can use [spark-csv](https://spark-packages.org/package/databricks/spark-csv), a third-party package from [SparkPackages](https://spark-packages.org/). The documentation and source code for [spark-csv](https://spark-packages.org/package/databricks/spark-csv) can be found on [GitHub](https://github.com/databricks/spark-csv). The Python API can be found [here](https://github.com/databricks/spark-csv#python-api).

(**Note**: In Spark 2.0, the CSV package is built into the DataFrame API.)

To use the [spark-csv](https://spark-packages.org/package/databricks/spark-csv) package, we use the [sqlContext.read.format()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrameReader.format) method to specify the input data source format: `'com.databricks.spark.csv'`

We can provide the [spark-csv](https://spark-packages.org/package/databricks/spark-csv) package with options using the [options()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrameReader.options) method. The available options are listed in the GitHub documentation [here](https://github.com/databricks/spark-csv#features).

We will use the following three options:
- `delimiter='\t'` because our data is tab delimited
- `header='true'` because our data has a header row
- `inferschema='true'` because we believe that all of the data is double values, so the package can dynamically infer the type of each column. *Note that this will require two pass over the data.*


The last component of creating the DataFrame is to specify the location of the data source using the [load()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrameReader.load) method: `"/databricks-datasets/power-plant/data"`

Putting everything together, we will use an operation of the following form:

  `sqlContext.read.format().options().load()`

### Exercise 2(b)

**TODO**: Create a DataFrame from the data.

*Hint*: Use the above template and fill in each of the methods.

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code.
plantDF = sqlContext.read.format('com.databricks.spark.csv').options(delimiter='\t',header='true',inferschema='true').load("/databricks-datasets/power-plant/data")

In [0]:
# Initialize the Test class
import hashlib

class TestFailure(Exception):
    pass
class PrivateTestFailure(Exception):
    pass

class Test(object):
    passed = 0
    numTests = 0
    failFast = False
    private = False

    @classmethod
    def setFailFast(cls):
        cls.failFast = True

    @classmethod
    def setPrivateMode(cls):
        cls.private = True

    @classmethod
    def assertTrue(cls, result, msg=""):
        cls.numTests += 1
        if result == True:
            cls.passed += 1
            print("1 test passed.")
        else:
            print("1 test failed. " + msg)
            if cls.failFast:
                if cls.private:
                    raise PrivateTestFailure(msg)
                else:
                    raise TestFailure(msg)

    @classmethod
    def assertEquals(cls, var, val, msg=""):
        cls.assertTrue(var == val, msg)

    @classmethod
    def assertEqualsHashed(cls, var, hashed_val, msg=""):
        cls.assertEquals(cls._hash(var), hashed_val, msg)

    @classmethod
    def printStats(cls):
        print("{0} / {1} test(s) passed.".format(cls.passed, cls.numTests))

    @classmethod
    def _hash(cls, x):
        return hashlib.sha1(str(x).encode('utf-8')).hexdigest()

In [0]:
expected = set([(s, 'double') for s in ('AP', 'AT', 'PE', 'RH', 'V')])
Test.assertEquals(expected, set(plantDF.dtypes), "Incorrect schema for powerPlantDF")

1 test passed.


Check the names and types of the columns using the [dtypes](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrame.dtypes) method.

In [0]:
print(plantDF.dtypes)

[('AT', 'double'), ('V', 'double'), ('AP', 'double'), ('RH', 'double'), ('PE', 'double')]


We can examine the data using the display() method.

In [0]:
display(plantDF)

AT V AP RH PE 14.96 41.76 1024.07 73.17 463.26 25.18 62.96 1020.04 59.08 444.37 5.11 39.4 1012.16 92.14 488.56 20.86 57.32 1010.24 76.64 446.48 10.82 37.5 1009.23 96.62 473.9 26.27 59.44 1012.23 58.77 443.67 15.89 43.96 1014.02 75.24 467.35 9.48 44.71 1019.12 66.43 478.42 14.64 45.0 1021.78 41.25 475.98 11.74 43.56 1015.14 70.72 477.5 17.99 43.72 1008.64 75.04 453.02 20.14 46.93 1014.66 64.22 453.99 24.34 73.5 1011.31 84.15 440.29 25.71 58.59 1012.77 61.83 451.28 26.19 69.34 1009.48 87.59 433.99 21.42 43.79 1015.76 43.08 462.19 18.21 45.0 1022.86 48.84 467.54 11.04 41.74 1022.6 77.51 477.2 14.45 52.75 1023.97 63.59 459.85 13.97 38.47 1015.15 55.28 464.3 17.76 42.42 1009.09 66.26 468.27 5.41 40.07 1019.16 64.77 495.24 7.76 42.28 1008.52 83.31 483.8 27.23 63.9 1014.3 47.19 443.61 27.36 48.6 1003.18 54.93 436.06 27.47 70.72 1009.97 74.62 443.25 14.6 39.31 1011.11 72.52 464.16 7.91 39.96 1023.57 88.44 475.52 5.81 35.79 1012.14 92.28 484.41 30.53 65.18 1012.69 41.85 437.89 23.87 63.94 1019.02 44.28 445.11 26.09 58.41 1013.64 64.58 438.86 29.27 66.85 1011.11 63.25 440.98 27.38 74.16 1010.08 78.61 436.65 24.81 63.94 1018.76 44.51 444.26 12.75 44.03 1007.29 89.46 465.86 24.66 63.73 1011.4 74.52 444.37 16.38 47.45 1010.08 88.86 450.69 13.91 39.35 1014.69 75.51 469.02 23.18 51.3 1012.04 78.64 448.86 22.47 47.45 1007.62 76.65 447.14 13.39 44.85 1017.24 80.44 469.18 9.28 41.54 1018.33 79.89 482.8 11.82 42.86 1014.12 88.28 476.7 10.27 40.64 1020.63 84.6 474.99 22.92 63.94 1019.28 42.69 444.22 16.0 37.87 1020.24 78.41 461.33 21.22 43.43 1010.96 61.07 448.06 13.46 44.71 1014.51 50.0 474.6 9.39 40.11 1029.14 77.29 473.05 31.07 73.5 1010.58 43.66 432.06 12.82 38.62 1018.71 83.8 467.41 32.57 78.92 1011.6 66.47 430.12 8.11 42.18 1014.82 93.09 473.62 13.92 39.39 1012.94 80.52 471.81 23.04 59.43 1010.23 68.99 442.99 27.31 64.44 1014.65 57.27 442.77 5.91 39.33 1010.18 95.53 491.49 25.26 61.08 1013.68 71.72 447.46 27.97 58.84 1002.25 57.88 446.11 26.08 52.3 1007.03 63.34 442.44 29.01 65.71 1013.61 48.07 446.22 12.18 40.1 1016.67 91.87 471.49 13.76 45.87 1008.89 87.27 463.5 25.5 58.79 1016.02 64.4 440.01 28.26 65.34 1014.56 43.4 441.03 21.39 62.96 1019.49 72.24 452.68 7.26 40.69 1020.43 90.22 474.91 10.54 34.03 1018.71 74.0 478.77 27.71 74.34 998.14 71.85 434.2 23.11 68.3 1017.83 86.62 437.91 7.51 41.01 1024.61 97.41 477.61 26.46 74.67 1016.65 84.44 431.65 29.34 74.34 998.58 81.55 430.57 10.32 42.28 1008.82 75.66 481.09 22.74 61.02 1009.56 79.41 445.56 13.48 39.85 1012.71 58.91 475.74 25.52 69.75 1010.36 90.06 435.12 21.58 67.25 1017.39 79.0 446.15 27.66 76.86 1001.31 69.47 436.64 26.96 69.45 1013.89 51.47 436.69 12.29 42.18 1016.53 83.13 468.75 15.86 43.02 1012.18 40.33 466.6 13.87 45.08 1024.42 81.69 465.48 24.09 73.68 1014.93 94.55 441.34 20.45 69.45 1012.53 91.81 441.83 15.07 39.3 1019.0 63.62 464.7 32.72 69.75 1009.6 49.35 437.99 18.23 58.96 1015.55 69.61 459.12 35.56 68.94 1006.56 38.75 429.69 18.36 51.43 1010.57 90.17 459.8 26.35 64.05 1009.81 81.24 433.63 25.92 60.95 1014.62 48.46 442.84 8.01 41.66 1014.49 76.72 485.13 19.63 52.72 1025.09 51.16 459.12 20.02 67.32 1012.05 76.34 445.31 10.08 40.72 1022.7 67.3 480.8 27.23 66.48 1005.23 52.38 432.55 23.37 63.77 1013.42 76.44 443.86 18.74 59.21 1018.3 91.55 449.77 14.81 43.69 1017.19 71.9 470.71 23.1 51.3 1011.93 80.05 452.17 10.72 41.38 1021.6 63.77 478.29 29.46 71.94 1006.96 62.26 428.54 8.1 40.64 1020.66 89.04 478.27 27.29 62.66 1007.63 58.02 439.58 17.1 49.69 1005.53 81.82 457.32 11.49 44.2 1018.79 91.14 475.51 23.69 65.59 1010.85 88.92 439.66 13.51 40.89 1011.03 84.83 471.99 9.64 39.35 1015.1 91.76 479.81 25.65 78.92 1010.83 86.56 434.78 21.59 61.87 1011.18 57.21 446.58 27.98 58.33 1013.92 54.25 437.76 18.8 39.72 1001.24 63.8 459.36 18.28 44.71 1016.99 33.71 462.28 13.55 43.48 1016.08 67.25 464.33 22.99 46.21 1010.71 60.11 444.36 23.94 59.39 1014.32 74.55 438.64 13.74 34.03 1018.69 67.34 470.49 21.3 41.1 1001.86 42.75 455.13 27.54 66.93 1017.06 55.2 450.22 24.81 63.73 1009.34 83.61 440.43 4.9

### Part 2: Alternative Method to Load your Data
Instead of having [spark-csv](https://spark-packages.org/package/databricks/spark-csv) infer the types of the columns, we can specify the schema as a [DataType](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.types.DataType), which is a list of [StructField](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.types.StructType).

You can find a list of types in the [pyspark.sql.types](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#module-pyspark.sql.types) module. For our data, we will use [DoubleType()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.types.DoubleType).

For example, to specify that a column's name and type, we use: `StructField(`_name_`,` _type_`, True)`. (The third parameter, `True`, signifies that the column is nullable.)

### Exercise 2(c)

Create a custom schema for the power plant data.

In [0]:
# TODO: Fill in the custom schema.
from pyspark.sql.types import *

# Custom Schema for Power Plant
customSchema = StructType([ \
    StructField("AT", DoubleType(), True), \
    StructField ('V', DoubleType(), True), \
    StructField ('AP', DoubleType(), True), \
    StructField ('RH', DoubleType(), True),\
    StructField ('PE', DoubleType(), True)\
    ])

In [0]:
# TEST
Test.assertEquals(set([f.name for f in customSchema.fields]), set(['AT', 'V', 'AP', 'RH', 'PE']), 'Incorrect column names in schema.')
Test.assertEquals(set([f.dataType for f in customSchema.fields]), set([DoubleType(), DoubleType(), DoubleType(), DoubleType(), DoubleType()]), 'Incorrect column types in schema.')

1 test passed.
1 test passed.


### Exercise 2(d)

Now, let's use the schema to read the data. To do this, we will modify the earlier `sqlContext.read.format` step. We can specify the schema by:
- Adding `schema = customSchema` to the load method (use a comma and add it after the file name)
- Removing the `inferschema='true'`option because we are explicitly specifying the schema

In [0]:
# TODO: Use the schema you created above to load the data again.
altPlantDF = sqlContext.read.format('com.databricks.spark.csv').\
                            options(delimiter='\t',header = 'true').\
                            load("/databricks-datasets/power-plant/data/",schema = customSchema)

In [0]:
# TEST
expected = set([(s, 'double') for s in ('AP', 'AT', 'PE', 'RH', 'V')])
Test.assertEquals(expected, set(altPlantDF.dtypes), "Incorrect schema for powerPlantDF")

1 test passed.


Note that no Spark jobs are launched this time. That is because we specified the schema, so the [spark-csv](https://spark-packages.org/package/databricks/spark-csv) package does not have to read the data to infer the schema. We can use the [dtypes](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrame.dtypes) method to examine the names and types of the columns. They should be identical to the names and types of the columns that were earlier inferred from the data.

When you run the following cell, data would not be read.

In [0]:
print(altPlantDF.dtypes)

[('AT', 'double'), ('V', 'double'), ('AP', 'double'), ('RH', 'double'), ('PE', 'double')]


Now we can examine the data using the display() method. *Note that this operation will cause the data to be read and the DataFrame will be created.*

In [0]:
display(altPlantDF)

AT V AP RH PE 14.96 41.76 1024.07 73.17 463.26 25.18 62.96 1020.04 59.08 444.37 5.11 39.4 1012.16 92.14 488.56 20.86 57.32 1010.24 76.64 446.48 10.82 37.5 1009.23 96.62 473.9 26.27 59.44 1012.23 58.77 443.67 15.89 43.96 1014.02 75.24 467.35 9.48 44.71 1019.12 66.43 478.42 14.64 45.0 1021.78 41.25 475.98 11.74 43.56 1015.14 70.72 477.5 17.99 43.72 1008.64 75.04 453.02 20.14 46.93 1014.66 64.22 453.99 24.34 73.5 1011.31 84.15 440.29 25.71 58.59 1012.77 61.83 451.28 26.19 69.34 1009.48 87.59 433.99 21.42 43.79 1015.76 43.08 462.19 18.21 45.0 1022.86 48.84 467.54 11.04 41.74 1022.6 77.51 477.2 14.45 52.75 1023.97 63.59 459.85 13.97 38.47 1015.15 55.28 464.3 17.76 42.42 1009.09 66.26 468.27 5.41 40.07 1019.16 64.77 495.24 7.76 42.28 1008.52 83.31 483.8 27.23 63.9 1014.3 47.19 443.61 27.36 48.6 1003.18 54.93 436.06 27.47 70.72 1009.97 74.62 443.25 14.6 39.31 1011.11 72.52 464.16 7.91 39.96 1023.57 88.44 475.52 5.81 35.79 1012.14 92.28 484.41 30.53 65.18 1012.69 41.85 437.89 23.87 63.94 1019.02 44.28 445.11 26.09 58.41 1013.64 64.58 438.86 29.27 66.85 1011.11 63.25 440.98 27.38 74.16 1010.08 78.61 436.65 24.81 63.94 1018.76 44.51 444.26 12.75 44.03 1007.29 89.46 465.86 24.66 63.73 1011.4 74.52 444.37 16.38 47.45 1010.08 88.86 450.69 13.91 39.35 1014.69 75.51 469.02 23.18 51.3 1012.04 78.64 448.86 22.47 47.45 1007.62 76.65 447.14 13.39 44.85 1017.24 80.44 469.18 9.28 41.54 1018.33 79.89 482.8 11.82 42.86 1014.12 88.28 476.7 10.27 40.64 1020.63 84.6 474.99 22.92 63.94 1019.28 42.69 444.22 16.0 37.87 1020.24 78.41 461.33 21.22 43.43 1010.96 61.07 448.06 13.46 44.71 1014.51 50.0 474.6 9.39 40.11 1029.14 77.29 473.05 31.07 73.5 1010.58 43.66 432.06 12.82 38.62 1018.71 83.8 467.41 32.57 78.92 1011.6 66.47 430.12 8.11 42.18 1014.82 93.09 473.62 13.92 39.39 1012.94 80.52 471.81 23.04 59.43 1010.23 68.99 442.99 27.31 64.44 1014.65 57.27 442.77 5.91 39.33 1010.18 95.53 491.49 25.26 61.08 1013.68 71.72 447.46 27.97 58.84 1002.25 57.88 446.11 26.08 52.3 1007.03 63.34 442.44 29.01 65.71 1013.61 48.07 446.22 12.18 40.1 1016.67 91.87 471.49 13.76 45.87 1008.89 87.27 463.5 25.5 58.79 1016.02 64.4 440.01 28.26 65.34 1014.56 43.4 441.03 21.39 62.96 1019.49 72.24 452.68 7.26 40.69 1020.43 90.22 474.91 10.54 34.03 1018.71 74.0 478.77 27.71 74.34 998.14 71.85 434.2 23.11 68.3 1017.83 86.62 437.91 7.51 41.01 1024.61 97.41 477.61 26.46 74.67 1016.65 84.44 431.65 29.34 74.34 998.58 81.55 430.57 10.32 42.28 1008.82 75.66 481.09 22.74 61.02 1009.56 79.41 445.56 13.48 39.85 1012.71 58.91 475.74 25.52 69.75 1010.36 90.06 435.12 21.58 67.25 1017.39 79.0 446.15 27.66 76.86 1001.31 69.47 436.64 26.96 69.45 1013.89 51.47 436.69 12.29 42.18 1016.53 83.13 468.75 15.86 43.02 1012.18 40.33 466.6 13.87 45.08 1024.42 81.69 465.48 24.09 73.68 1014.93 94.55 441.34 20.45 69.45 1012.53 91.81 441.83 15.07 39.3 1019.0 63.62 464.7 32.72 69.75 1009.6 49.35 437.99 18.23 58.96 1015.55 69.61 459.12 35.56 68.94 1006.56 38.75 429.69 18.36 51.43 1010.57 90.17 459.8 26.35 64.05 1009.81 81.24 433.63 25.92 60.95 1014.62 48.46 442.84 8.01 41.66 1014.49 76.72 485.13 19.63 52.72 1025.09 51.16 459.12 20.02 67.32 1012.05 76.34 445.31 10.08 40.72 1022.7 67.3 480.8 27.23 66.48 1005.23 52.38 432.55 23.37 63.77 1013.42 76.44 443.86 18.74 59.21 1018.3 91.55 449.77 14.81 43.69 1017.19 71.9 470.71 23.1 51.3 1011.93 80.05 452.17 10.72 41.38 1021.6 63.77 478.29 29.46 71.94 1006.96 62.26 428.54 8.1 40.64 1020.66 89.04 478.27 27.29 62.66 1007.63 58.02 439.58 17.1 49.69 1005.53 81.82 457.32 11.49 44.2 1018.79 91.14 475.51 23.69 65.59 1010.85 88.92 439.66 13.51 40.89 1011.03 84.83 471.99 9.64 39.35 1015.1 91.76 479.81 25.65 78.92 1010.83 86.56 434.78 21.59 61.87 1011.18 57.21 446.58 27.98 58.33 1013.92 54.25 437.76 18.8 39.72 1001.24 63.8 459.36 18.28 44.71 1016.99 33.71 462.28 13.55 43.48 1016.08 67.25 464.33 22.99 46.21 1010.71 60.11 444.36 23.94 59.39 1014.32 74.55 438.64 13.74 34.03 1018.69 67.34 470.49 21.3 41.1 1001.86 42.75 455.13 27.54 66.93 1017.06 55.2 450.22 24.81 63.73 1009.34 83.61 440.43 4.9

## Part 3: Explore Your Data
Now that your data is loaded, the next step is to explore it and perform some basic analysis and visualizations.

This is a step that you should always perform **before** trying to fit a model to the data, as this step will often lead to important insights about your data.

First, let's register our DataFrame as an SQL table named `plant_dataset`.  Because you may run this lab multiple times, we'll take the precaution of removing any existing tables first.

We can delete any existing `plant_dataset` SQL table using the SQL command: `DROP TABLE IF EXISTS plant_dataset` (we also need to to delete any Hive data associated with the table, which we can do with a Databricks file system operation).

Once any prior table is removed, we can register our DataFrame as a SQL table using [sqlContext.registerDataFrameAsTable()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.SQLContext.registerDataFrameAsTable).

### 3(a)

**TODO**: Execute the prepared code in the following cell.

In [0]:
sqlContext.sql("DROP TABLE IF EXISTS plant_dataset")
dbutils.fs.rm("dbfs:/user/hive/warehouse/plant_dataset", True)
sqlContext.registerDataFrameAsTable(plantDF, "plant_dataset")

Now that our DataFrame exists as a SQL table, we can explore it using SQL commands. This [mini tutorial](https://tutorialzine.com/2016/01/learn-sql-in-20-minutes) could help refeshing the SQL knowledge, and the top three sections therein are enough for this lab.

To execute SQL in a cell, we use the `%sql` operator. The following cell is an example of using SQL to query the rows of the SQL table.

**NOTE**: `%sql` is a Databricks-only command. It calls `sqlContext.sql()` and passes the results to the Databricks-only `display()` function. These two statements are equivalent:

`%sql SELECT * FROM plant_dataset`

`display(sqlContext.sql("SELECT * FROM plant_dataset"))`

### 3(b)

**TODO**: Execute the prepared code in the following cell.

In [0]:
%sql
-- We can use %sql to query the rows
SELECT * FROM plant_dataset

AT V AP RH PE 14.96 41.76 1024.07 73.17 463.26 25.18 62.96 1020.04 59.08 444.37 5.11 39.4 1012.16 92.14 488.56 20.86 57.32 1010.24 76.64 446.48 10.82 37.5 1009.23 96.62 473.9 26.27 59.44 1012.23 58.77 443.67 15.89 43.96 1014.02 75.24 467.35 9.48 44.71 1019.12 66.43 478.42 14.64 45.0 1021.78 41.25 475.98 11.74 43.56 1015.14 70.72 477.5 17.99 43.72 1008.64 75.04 453.02 20.14 46.93 1014.66 64.22 453.99 24.34 73.5 1011.31 84.15 440.29 25.71 58.59 1012.77 61.83 451.28 26.19 69.34 1009.48 87.59 433.99 21.42 43.79 1015.76 43.08 462.19 18.21 45.0 1022.86 48.84 467.54 11.04 41.74 1022.6 77.51 477.2 14.45 52.75 1023.97 63.59 459.85 13.97 38.47 1015.15 55.28 464.3 17.76 42.42 1009.09 66.26 468.27 5.41 40.07 1019.16 64.77 495.24 7.76 42.28 1008.52 83.31 483.8 27.23 63.9 1014.3 47.19 443.61 27.36 48.6 1003.18 54.93 436.06 27.47 70.72 1009.97 74.62 443.25 14.6 39.31 1011.11 72.52 464.16 7.91 39.96 1023.57 88.44 475.52 5.81 35.79 1012.14 92.28 484.41 30.53 65.18 1012.69 41.85 437.89 23.87 63.94 1019.02 44.28 445.11 26.09 58.41 1013.64 64.58 438.86 29.27 66.85 1011.11 63.25 440.98 27.38 74.16 1010.08 78.61 436.65 24.81 63.94 1018.76 44.51 444.26 12.75 44.03 1007.29 89.46 465.86 24.66 63.73 1011.4 74.52 444.37 16.38 47.45 1010.08 88.86 450.69 13.91 39.35 1014.69 75.51 469.02 23.18 51.3 1012.04 78.64 448.86 22.47 47.45 1007.62 76.65 447.14 13.39 44.85 1017.24 80.44 469.18 9.28 41.54 1018.33 79.89 482.8 11.82 42.86 1014.12 88.28 476.7 10.27 40.64 1020.63 84.6 474.99 22.92 63.94 1019.28 42.69 444.22 16.0 37.87 1020.24 78.41 461.33 21.22 43.43 1010.96 61.07 448.06 13.46 44.71 1014.51 50.0 474.6 9.39 40.11 1029.14 77.29 473.05 31.07 73.5 1010.58 43.66 432.06 12.82 38.62 1018.71 83.8 467.41 32.57 78.92 1011.6 66.47 430.12 8.11 42.18 1014.82 93.09 473.62 13.92 39.39 1012.94 80.52 471.81 23.04 59.43 1010.23 68.99 442.99 27.31 64.44 1014.65 57.27 442.77 5.91 39.33 1010.18 95.53 491.49 25.26 61.08 1013.68 71.72 447.46 27.97 58.84 1002.25 57.88 446.11 26.08 52.3 1007.03 63.34 442.44 29.01 65.71 1013.61 48.07 446.22 12.18 40.1 1016.67 91.87 471.49 13.76 45.87 1008.89 87.27 463.5 25.5 58.79 1016.02 64.4 440.01 28.26 65.34 1014.56 43.4 441.03 21.39 62.96 1019.49 72.24 452.68 7.26 40.69 1020.43 90.22 474.91 10.54 34.03 1018.71 74.0 478.77 27.71 74.34 998.14 71.85 434.2 23.11 68.3 1017.83 86.62 437.91 7.51 41.01 1024.61 97.41 477.61 26.46 74.67 1016.65 84.44 431.65 29.34 74.34 998.58 81.55 430.57 10.32 42.28 1008.82 75.66 481.09 22.74 61.02 1009.56 79.41 445.56 13.48 39.85 1012.71 58.91 475.74 25.52 69.75 1010.36 90.06 435.12 21.58 67.25 1017.39 79.0 446.15 27.66 76.86 1001.31 69.47 436.64 26.96 69.45 1013.89 51.47 436.69 12.29 42.18 1016.53 83.13 468.75 15.86 43.02 1012.18 40.33 466.6 13.87 45.08 1024.42 81.69 465.48 24.09 73.68 1014.93 94.55 441.34 20.45 69.45 1012.53 91.81 441.83 15.07 39.3 1019.0 63.62 464.7 32.72 69.75 1009.6 49.35 437.99 18.23 58.96 1015.55 69.61 459.12 35.56 68.94 1006.56 38.75 429.69 18.36 51.43 1010.57 90.17 459.8 26.35 64.05 1009.81 81.24 433.63 25.92 60.95 1014.62 48.46 442.84 8.01 41.66 1014.49 76.72 485.13 19.63 52.72 1025.09 51.16 459.12 20.02 67.32 1012.05 76.34 445.31 10.08 40.72 1022.7 67.3 480.8 27.23 66.48 1005.23 52.38 432.55 23.37 63.77 1013.42 76.44 443.86 18.74 59.21 1018.3 91.55 449.77 14.81 43.69 1017.19 71.9 470.71 23.1 51.3 1011.93 80.05 452.17 10.72 41.38 1021.6 63.77 478.29 29.46 71.94 1006.96 62.26 428.54 8.1 40.64 1020.66 89.04 478.27 27.29 62.66 1007.63 58.02 439.58 17.1 49.69 1005.53 81.82 457.32 11.49 44.2 1018.79 91.14 475.51 23.69 65.59 1010.85 88.92 439.66 13.51 40.89 1011.03 84.83 471.99 9.64 39.35 1015.1 91.76 479.81 25.65 78.92 1010.83 86.56 434.78 21.59 61.87 1011.18 57.21 446.58 27.98 58.33 1013.92 54.25 437.76 18.8 39.72 1001.24 63.8 459.36 18.28 44.71 1016.99 33.71 462.28 13.55 43.48 1016.08 67.25 464.33 22.99 46.21 1010.71 60.11 444.36 23.94 59.39 1014.32 74.55 438.64 13.74 34.03 1018.69 67.34 470.49 21.3 41.1 1001.86 42.75 455.13 27.54 66.93 1017.06 55.2 450.22 24.81 63.73 1009.34 83.61 440.43 4.9

### 3(c)

Use the SQL `desc` command to describe the schema, by executing the following cell.

In [0]:
%sql
desc plant_dataset

col_name data_type comment AT double null V double null AP double null RH double null PE double null

**Schema Definition**

Once again, here's our schema definition:

- AT = Atmospheric Temperature in C
- V = Exhaust Vacuum Speed
- AP = Atmospheric Pressure
- RH = Relative Humidity
- PE = Power Output

PE is our label or target. This is the value we are trying to predict given the measurements.

*Reference [UCI Machine Learning Repository Combined Cycle Power Plant Data Set](https://archive.ics.uci.edu/ml/datasets/Combined+Cycle+Power+Plant)*

Let's perform some basic statistical analyses of all the columns.

We can get the DataFrame associated with a SQL table by using the [sqlContext.table()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrameReader.table) method and passing in the name of the SQL table. Then, we can use the DataFrame [describe()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrame.describe) method with no arguments to compute some basic statistics for each column like count, mean, max, min and standard deviation.

In [0]:
df = sqlContext.table("plant_dataset")

display(df.describe())

summary AT V AP RH PE count 47840 47840 47840 47840 47840 mean 19.651231187290996 54.30580372073594 1013.2590781772572 73.30897784280918 454.36500940635506 stddev 7.452161658340004 12.707361709685806 5.938535418520816 14.599658352081477 17.06628146683769 min 1.81 25.36 992.89 25.56 420.26 max 37.11 81.56 1033.3 100.16 495.76

##Part 4: Visualize Your Data

To understand our data, we will look for correlations between features and the label.  This can be important when choosing a model.  E.g., if features and a label are linearly correlated, a linear model like Linear Regression can do well; if the relationship is very non-linear, more complex models such as Decision Trees can be better. We can use Databrick's built in visualization to view each of our predictors in relation to the label column as a scatter plot to see the correlation between the predictors and the label.

### Exercise 4(a)

** Add figures to the following: **
Let's see if there is a corellation between Temperature and Power Output. We can use a SQL query to create a new table consisting of only the AtmosphericTemperature (AT) and PowerOutput (PE) columns, and then use a scatter plot with AtmosphericTemperature on the Y axis and PowerOutput on the X axis to visualize the relationship (if any) between AtmosphericTemperature and PowerOutput.


Perform the following steps:

- Run the following cell
- Click on the drop down next to the "Bar chart" icon a select "Scatter" to turn the table into a Scatter plot

<img src="http://spark-mooc.github.io/web-assets/images/cs110x/change-plot-type-scatter.png" style="border: 1px solid #999999"/>

- Click on "Plot Options..."
- In the Values box, click on "Temperature" and drag it before "Power", as shown below:

<img src="https://raw.githubusercontent.com/hkust-comp4651-2018f/assets/master/assignment-5/customize_plot_small.png" style="border: 1px solid #999999"/>

- Apply your changes by clicking the Apply button
- Increase the size of the graph by clicking and dragging the size control

In [0]:
%sql
select AT as AtmosphericTemperature, PE as PowerOutput from plant_dataset

AtmosphericTemperature PowerOutput 14.96 463.26 25.18 444.37 5.11 488.56 20.86 446.48 10.82 473.9 26.27 443.67 15.89 467.35 9.48 478.42 14.64 475.98 11.74 477.5 17.99 453.02 20.14 453.99 24.34 440.29 25.71 451.28 26.19 433.99 21.42 462.19 18.21 467.54 11.04 477.2 14.45 459.85 13.97 464.3 17.76 468.27 5.41 495.24 7.76 483.8 27.23 443.61 27.36 436.06 27.47 443.25 14.6 464.16 7.91 475.52 5.81 484.41 30.53 437.89 23.87 445.11 26.09 438.86 29.27 440.98 27.38 436.65 24.81 444.26 12.75 465.86 24.66 444.37 16.38 450.69 13.91 469.02 23.18 448.86 22.47 447.14 13.39 469.18 9.28 482.8 11.82 476.7 10.27 474.99 22.92 444.22 16.0 461.33 21.22 448.06 13.46 474.6 9.39 473.05 31.07 432.06 12.82 467.41 32.57 430.12 8.11 473.62 13.92 471.81 23.04 442.99 27.31 442.77 5.91 491.49 25.26 447.46 27.97 446.11 26.08 442.44 29.01 446.22 12.18 471.49 13.76 463.5 25.5 440.01 28.26 441.03 21.39 452.68 7.26 474.91 10.54 478.77 27.71 434.2 23.11 437.91 7.51 477.61 26.46 431.65 29.34 430.57 10.32 481.09 22.74 445.56 13.48 475.74 25.52 435.12 21.58 446.15 27.66 436.64 26.96 436.69 12.29 468.75 15.86 466.6 13.87 465.48 24.09 441.34 20.45 441.83 15.07 464.7 32.72 437.99 18.23 459.12 35.56 429.69 18.36 459.8 26.35 433.63 25.92 442.84 8.01 485.13 19.63 459.12 20.02 445.31 10.08 480.8 27.23 432.55 23.37 443.86 18.74 449.77 14.81 470.71 23.1 452.17 10.72 478.29 29.46 428.54 8.1 478.27 27.29 439.58 17.1 457.32 11.49 475.51 23.69 439.66 13.51 471.99 9.64 479.81 25.65 434.78 21.59 446.58 27.98 437.76 18.8 459.36 18.28 462.28 13.55 464.33 22.99 444.36 23.94 438.64 13.74 470.49 21.3 455.13 27.54 450.22 24.81 440.43 4.97 482.98 15.22 460.44 23.88 444.97 33.01 433.94 25.98 439.73 28.18 434.48 21.67 442.33 17.67 457.67 21.37 454.66 28.69 432.21 16.61 457.66 27.91 435.21 20.97 448.22 10.8 475.51 20.61 446.53 25.45 441.3 30.16 433.54 4.99 472.52 10.51 474.77 33.79 435.1 21.34 450.74 23.4 442.7 32.21 426.56 14.26 463.71 27.71 447.06 21.95 452.27 25.76 445.78 23.68 438.65 8.28 480.15 23.44 447.19 25.32 443.04 3.94 488.81 17.3 455.75 18.2 455.86 21.43 457.68 11.16 479.11 30.38 432.84 23.36 448.37 21.69 447.06 23.62 443.53 21.87 445.21 29.25 441.7 20.03 450.93 18.14 451.44 24.23 441.29 18.11 458.85 6.57 481.46 12.56 467.19 13.4 461.54 27.1 439.08 14.28 467.22 16.29 468.8 31.24 426.93 10.57 474.65 13.8 468.97 25.3 433.97 18.06 450.53 25.42 444.51 15.07 469.03 11.75 466.56 20.23 457.57 27.31 440.13 28.57 433.24 17.9 452.55 23.83 443.29 27.92 431.76 17.34 454.97 17.94 456.7 6.4 486.03 11.78 472.79 20.28 452.03 21.04 443.41 25.11 441.93 30.28 432.64 8.14 480.25 16.86 466.68 6.25 494.39 22.35 454.72 17.98 448.71 21.19 469.76 20.94 450.71 24.23 444.01 19.18 453.2 20.88 450.87 23.67 441.73 14.12 465.09 25.23 447.28 6.54 491.16 20.08 450.98 24.67 446.3 27.82 436.48 15.55 460.84 24.26 442.56 13.45 467.3 11.06 479.13 24.91 441.15 22.39 445.52 11.95 475.4 14.85 469.3 10.11 463.57 23.67 445.32 16.14 461.03 15.11 466.74 24.14 444.04 30.08 434.01 14.77 465.23 27.6 440.6 13.89 466.74 26.85 433.48 12.41 473.59 13.08 474.81 18.93 454.75 20.5 452.94 30.72 435.83 7.55 482.19 13.49 466.66 15.62 462.59 24.8 447.82 10.03 462.73 22.43 447.98 14.95 462.72 24.78 442.42 23.2 444.69 14.01 466.7 19.4 453.84 30.15 436.92 6.91 486.37 29.04 440.43 26.02 446.82 5.89 484.91 26.52 437.76 28.53 438.91 16.59 464.19 22.95 442.19 23.96 446.86 17.48 457.15 6.69 482.57 10.25 476.03 28.87 428.89 12.04 472.7 22.58 445.6 15.12 464.78 25.48 440.42 27.87 428.41 23.72 438.5 25.0 438.28 8.42 476.29 22.46 448.46 29.92 438.99 11.68 471.8 14.04 471.81 19.86 449.82 25.99 442.14 23.42 441.46 10.6 477.62 20.97 446.76 14.14 472.52 8.56 471.58 24.86 440.85 29.0 431.37 27.59 437.33 10.45 469.22 8.51 471.11 29.82 439.17 22.56 445.33 11.38 473.71 20.25 452.66 22.42 440.99 14.85 467.42 25.62 444.14 19.85 457.17 13.67 467.87 24.39 442.04 16.07 471.36 11.6 460.7 31.38 431.33 29.91 432.6 19.67 447.61 27.18 443.87 21.39 446.87 10.45 465.74 19.46 447.86 23.55 447.65 23.35 437.87 9.26 483.51 10.3 479.65 20.94 455.16 23.13 431.91 12.77 470.68 28

It looks like there is strong linear correlation between Temperature and Power Output.

** ASIDE: A quick physics lesson**: This correlation is to be expected as the second law of thermodynamics puts a fundamental limit on the [thermal efficiency](https://en.wikipedia.org/wiki/Thermal_efficiency) of all heat-based engines. The limiting factors are:
 - The temperature at which the heat enters the engine \\( T_{H} \\)
 - The temperature of the environment into which the engine exhausts its waste heat \\( T_C \\)

Our temperature measurements are the temperature of the environment. From [Carnot's theorem](https://en.wikipedia.org/wiki/Carnot%27s_theorem_%28thermodynamics%29), no heat engine working between these two temperatures can exceed the Carnot Cycle efficiency:
\\[ n_{th} \le 1 - \frac{T_C}{T_H}  \\]

Note that as the environmental temperature increases, the efficiency decreases -- _this is the effect that we see in the above graph._

### Exercise 4(b)

Use SQL to create a scatter plot of PowerOutput(PE) as a function of VacuumSpeed (V).
Name the y-axis "PowerOutput" and the x-axis "VacuumSpeed"

In [0]:
%sql
-- TODO: Replace <FILL_IN> with the appropriate SQL command.
select PE as PowerOutput, V as VacuumSpeed from plant_dataset

PowerOutput VacuumSpeed 463.26 41.76 444.37 62.96 488.56 39.4 446.48 57.32 473.9 37.5 443.67 59.44 467.35 43.96 478.42 44.71 475.98 45.0 477.5 43.56 453.02 43.72 453.99 46.93 440.29 73.5 451.28 58.59 433.99 69.34 462.19 43.79 467.54 45.0 477.2 41.74 459.85 52.75 464.3 38.47 468.27 42.42 495.24 40.07 483.8 42.28 443.61 63.9 436.06 48.6 443.25 70.72 464.16 39.31 475.52 39.96 484.41 35.79 437.89 65.18 445.11 63.94 438.86 58.41 440.98 66.85 436.65 74.16 444.26 63.94 465.86 44.03 444.37 63.73 450.69 47.45 469.02 39.35 448.86 51.3 447.14 47.45 469.18 44.85 482.8 41.54 476.7 42.86 474.99 40.64 444.22 63.94 461.33 37.87 448.06 43.43 474.6 44.71 473.05 40.11 432.06 73.5 467.41 38.62 430.12 78.92 473.62 42.18 471.81 39.39 442.99 59.43 442.77 64.44 491.49 39.33 447.46 61.08 446.11 58.84 442.44 52.3 446.22 65.71 471.49 40.1 463.5 45.87 440.01 58.79 441.03 65.34 452.68 62.96 474.91 40.69 478.77 34.03 434.2 74.34 437.91 68.3 477.61 41.01 431.65 74.67 430.57 74.34 481.09 42.28 445.56 61.02 475.74 39.85 435.12 69.75 446.15 67.25 436.64 76.86 436.69 69.45 468.75 42.18 466.6 43.02 465.48 45.08 441.34 73.68 441.83 69.45 464.7 39.3 437.99 69.75 459.12 58.96 429.69 68.94 459.8 51.43 433.63 64.05 442.84 60.95 485.13 41.66 459.12 52.72 445.31 67.32 480.8 40.72 432.55 66.48 443.86 63.77 449.77 59.21 470.71 43.69 452.17 51.3 478.29 41.38 428.54 71.94 478.27 40.64 439.58 62.66 457.32 49.69 475.51 44.2 439.66 65.59 471.99 40.89 479.81 39.35 434.78 78.92 446.58 61.87 437.76 58.33 459.36 39.72 462.28 44.71 464.33 43.48 444.36 46.21 438.64 59.39 470.49 34.03 455.13 41.1 450.22 66.93 440.43 63.73 482.98 42.85 460.44 50.88 444.97 54.2 433.94 68.67 439.73 73.18 434.48 73.88 442.33 60.84 457.67 45.09 454.66 57.76 432.21 67.25 457.66 43.77 435.21 63.76 448.22 47.43 475.51 41.66 446.53 62.91 441.3 57.32 433.54 69.34 472.52 39.04 474.77 44.78 435.1 69.05 450.74 59.8 442.7 65.06 426.56 68.14 463.71 42.32 447.06 66.93 452.27 57.76 445.78 63.94 438.65 68.3 480.15 40.77 447.19 62.52 443.04 48.41 488.81 39.9 455.75 57.76 455.86 49.39 457.68 46.97 479.11 40.05 432.84 74.16 448.37 62.52 447.06 47.45 443.53 49.21 445.21 61.45 441.7 66.51 450.93 66.86 451.44 49.78 441.29 56.89 458.85 44.85 481.46 43.65 467.19 43.41 461.54 41.58 439.08 52.84 467.22 42.74 468.8 44.34 426.93 71.98 474.65 37.73 468.97 44.21 433.97 71.58 450.53 50.16 444.51 59.04 469.03 40.69 466.56 71.14 457.57 52.05 440.13 59.54 433.24 69.84 452.55 43.72 443.29 71.37 431.76 74.99 454.97 44.78 456.7 63.07 486.03 39.9 472.79 39.96 452.03 57.25 443.41 54.2 441.93 67.32 432.64 70.98 480.25 36.24 466.68 39.63 494.39 40.07 454.72 54.42 448.71 56.85 469.76 42.48 450.71 44.89 444.01 58.79 453.2 58.2 450.87 57.85 441.73 63.86 465.09 39.52 447.28 64.63 491.16 39.33 450.98 62.52 446.3 63.56 436.48 79.74 460.84 42.03 442.56 69.51 467.3 41.49 479.13 40.64 441.15 52.3 445.52 59.04 475.4 40.69 469.3 40.69 463.57 41.62 445.32 68.67 461.03 44.21 466.74 43.13 444.04 59.87 434.01 67.25 465.23 44.9 440.6 69.34 466.74 44.84 433.48 75.6 473.59 40.96 474.81 41.74 454.75 44.06 452.94 49.69 435.83 69.13 482.19 39.22 466.66 44.47 462.59 40.12 447.82 64.63 462.73 41.62 447.98 63.21 462.72 39.31 442.42 58.46 444.69 48.41 466.7 39.0 453.84 64.63 436.92 67.32 486.37 36.08 440.43 60.07 446.82 63.07 484.91 39.48 437.76 71.64 438.91 68.08 464.19 39.54 442.19 67.79 446.86 47.43 457.15 44.2 482.57 43.65 476.03 41.26 428.89 72.58 472.7 40.23 445.6 52.3 464.78 52.05 440.42 58.95 428.41 70.79 438.5 70.47 438.28 59.43 476.29 40.64 448.46 58.49 438.99 57.19 471.8 39.22 471.81 42.44 449.82 59.14 442.14 68.08 441.46 58.79 477.62 40.22 446.76 61.87 472.52 39.82 471.58 40.71 440.85 72.39 431.37 77.54 437.33 71.97 469.22 40.71 471.11 40.78 439.17 66.51 445.33 62.26 473.71 39.22 452.66 57.76 440.99 59.43 467.42 38.91 444.14 58.82 457.17 56.53 467.87 54.3 442.04 70.72 471.36 44.58 460.7 39.1 431.33 70.83 432.6 76.86 447.61 59.39 443.87 64.79 446.87 52.3 465.74 41.01 447.86 56.89 447.65 62.96 437.87 63.47 483.51 41.66 479.65 41.46 455.16 58.16 431.91 71.2

Let's continue exploring the relationships (if any) between the variables and Power Output.

### Exercise 4(c)

Use SQL to create a scatter plot of PowerOutput(PE) as a function of AtmosphericPressure (AP).
Name the y-axis "PowerOutput" and the x-axis "AtmosphericPressure"

In [0]:
%sql
-- TODO: Replace <FILL_IN> with the appropriate SQL command.
select PE as PowerOutput, AP as AtmosphericPressure from plant_dataset

PowerOutput AtmosphericPressure 463.26 1024.07 444.37 1020.04 488.56 1012.16 446.48 1010.24 473.9 1009.23 443.67 1012.23 467.35 1014.02 478.42 1019.12 475.98 1021.78 477.5 1015.14 453.02 1008.64 453.99 1014.66 440.29 1011.31 451.28 1012.77 433.99 1009.48 462.19 1015.76 467.54 1022.86 477.2 1022.6 459.85 1023.97 464.3 1015.15 468.27 1009.09 495.24 1019.16 483.8 1008.52 443.61 1014.3 436.06 1003.18 443.25 1009.97 464.16 1011.11 475.52 1023.57 484.41 1012.14 437.89 1012.69 445.11 1019.02 438.86 1013.64 440.98 1011.11 436.65 1010.08 444.26 1018.76 465.86 1007.29 444.37 1011.4 450.69 1010.08 469.02 1014.69 448.86 1012.04 447.14 1007.62 469.18 1017.24 482.8 1018.33 476.7 1014.12 474.99 1020.63 444.22 1019.28 461.33 1020.24 448.06 1010.96 474.6 1014.51 473.05 1029.14 432.06 1010.58 467.41 1018.71 430.12 1011.6 473.62 1014.82 471.81 1012.94 442.99 1010.23 442.77 1014.65 491.49 1010.18 447.46 1013.68 446.11 1002.25 442.44 1007.03 446.22 1013.61 471.49 1016.67 463.5 1008.89 440.01 1016.02 441.03 1014.56 452.68 1019.49 474.91 1020.43 478.77 1018.71 434.2 998.14 437.91 1017.83 477.61 1024.61 431.65 1016.65 430.57 998.58 481.09 1008.82 445.56 1009.56 475.74 1012.71 435.12 1010.36 446.15 1017.39 436.64 1001.31 436.69 1013.89 468.75 1016.53 466.6 1012.18 465.48 1024.42 441.34 1014.93 441.83 1012.53 464.7 1019.0 437.99 1009.6 459.12 1015.55 429.69 1006.56 459.8 1010.57 433.63 1009.81 442.84 1014.62 485.13 1014.49 459.12 1025.09 445.31 1012.05 480.8 1022.7 432.55 1005.23 443.86 1013.42 449.77 1018.3 470.71 1017.19 452.17 1011.93 478.29 1021.6 428.54 1006.96 478.27 1020.66 439.58 1007.63 457.32 1005.53 475.51 1018.79 439.66 1010.85 471.99 1011.03 479.81 1015.1 434.78 1010.83 446.58 1011.18 437.76 1013.92 459.36 1001.24 462.28 1016.99 464.33 1016.08 444.36 1010.71 438.64 1014.32 470.49 1018.69 455.13 1001.86 450.22 1017.06 440.43 1009.34 482.98 1014.02 460.44 1014.19 444.97 1012.81 433.94 1005.2 439.73 1012.28 434.48 1005.89 442.33 1017.93 457.67 1014.26 454.66 1018.8 432.21 1017.71 457.66 1012.25 435.21 1010.27 448.22 1007.64 475.51 1013.79 446.53 1013.24 441.3 1011.7 433.54 1007.67 472.52 1020.45 474.77 1012.59 435.1 1001.62 450.74 1016.92 442.7 1014.32 426.56 1003.34 463.71 1016.0 447.06 1016.85 452.27 1018.02 445.78 1018.49 438.65 1017.93 480.15 1011.55 447.19 1016.46 443.04 1008.47 488.81 1008.06 455.75 1016.26 455.86 1018.83 457.68 1013.94 479.11 1014.95 432.84 1007.44 448.37 1016.18 447.06 1007.56 443.53 1014.1 445.21 1011.13 441.7 1015.53 450.93 1013.05 451.44 1002.95 441.29 1012.32 458.85 1014.48 481.46 1018.24 467.19 1016.93 461.54 1020.5 439.08 1006.28 467.22 1028.79 468.8 1019.49 426.93 1004.66 474.65 1024.36 468.97 1022.93 433.97 1010.18 450.53 1009.52 444.51 1011.98 469.03 1015.29 466.56 1019.36 457.57 1012.15 440.13 1006.24 433.24 1003.57 452.55 1008.64 443.29 1002.04 431.76 1005.47 454.97 1007.81 456.7 1012.42 486.03 1007.75 472.79 1011.37 452.03 1010.12 443.41 1012.26 441.93 1014.49 432.64 1007.51 480.25 1013.15 466.68 1004.47 494.39 1020.19 454.72 1012.46 448.71 1012.28 469.76 1013.43 450.71 1009.64 444.01 1009.8 453.2 1017.46 450.87 1012.39 441.73 1019.67 465.09 1018.41 447.28 1020.59 491.16 1011.54 450.98 1017.99 446.3 1013.75 436.48 1008.37 460.84 1017.41 442.56 1013.43 467.3 1020.19 479.13 1021.47 441.15 1008.72 445.52 1011.78 475.4 1015.62 469.3 1014.91 463.57 1017.17 445.32 1006.71 461.03 1020.36 466.74 1014.99 444.04 1018.47 434.01 1017.6 465.23 1020.5 440.6 1009.63 466.74 1023.66 433.48 1017.43 473.59 1023.36 474.81 1020.75 454.75 1017.58 452.94 1009.6 435.83 1009.94 482.19 1014.53 466.66 1030.46 462.59 1013.03 447.82 1020.69 462.73 1014.55 447.98 1012.06 462.72 1009.15 442.42 1016.82 444.69 1008.64 466.7 1016.73 453.84 1020.38 436.92 1013.83 486.37 1021.82 440.43 1015.42 446.82 1010.94 484.91 1005.11 437.76 1008.27 438.91 1013.27 464.19 1007.97 442.19 1009.89 446.86 1008.38 457.15 1018.89 482.57 1020.14 476.03 1007.44 428.89 1008.69 472.7 1018.07 445.6 1009.04 464.78 1014.63 440.42 1017.02 428.41 1003.96 438.5 1010.65 

### Exercise 4(d)

Use SQL to create a scatter plot of PowerOutput(PE) as a function of RelativeHumidity(RH).
Name the y-axis "PowerOutput" and the x-axis "RelativeHumidity"

In [0]:
%sql
-- TODO: Replace <FILL_IN> with the appropriate SQL command.
select PE as PowerOutput, RH as RelativeHumidity from plant_dataset

PowerOutput RelativeHumidity 463.26 73.17 444.37 59.08 488.56 92.14 446.48 76.64 473.9 96.62 443.67 58.77 467.35 75.24 478.42 66.43 475.98 41.25 477.5 70.72 453.02 75.04 453.99 64.22 440.29 84.15 451.28 61.83 433.99 87.59 462.19 43.08 467.54 48.84 477.2 77.51 459.85 63.59 464.3 55.28 468.27 66.26 495.24 64.77 483.8 83.31 443.61 47.19 436.06 54.93 443.25 74.62 464.16 72.52 475.52 88.44 484.41 92.28 437.89 41.85 445.11 44.28 438.86 64.58 440.98 63.25 436.65 78.61 444.26 44.51 465.86 89.46 444.37 74.52 450.69 88.86 469.02 75.51 448.86 78.64 447.14 76.65 469.18 80.44 482.8 79.89 476.7 88.28 474.99 84.6 444.22 42.69 461.33 78.41 448.06 61.07 474.6 50.0 473.05 77.29 432.06 43.66 467.41 83.8 430.12 66.47 473.62 93.09 471.81 80.52 442.99 68.99 442.77 57.27 491.49 95.53 447.46 71.72 446.11 57.88 442.44 63.34 446.22 48.07 471.49 91.87 463.5 87.27 440.01 64.4 441.03 43.4 452.68 72.24 474.91 90.22 478.77 74.0 434.2 71.85 437.91 86.62 477.61 97.41 431.65 84.44 430.57 81.55 481.09 75.66 445.56 79.41 475.74 58.91 435.12 90.06 446.15 79.0 436.64 69.47 436.69 51.47 468.75 83.13 466.6 40.33 465.48 81.69 441.34 94.55 441.83 91.81 464.7 63.62 437.99 49.35 459.12 69.61 429.69 38.75 459.8 90.17 433.63 81.24 442.84 48.46 485.13 76.72 459.12 51.16 445.31 76.34 480.8 67.3 432.55 52.38 443.86 76.44 449.77 91.55 470.71 71.9 452.17 80.05 478.29 63.77 428.54 62.26 478.27 89.04 439.58 58.02 457.32 81.82 475.51 91.14 439.66 88.92 471.99 84.83 479.81 91.76 434.78 86.56 446.58 57.21 437.76 54.25 459.36 63.8 462.28 33.71 464.33 67.25 444.36 60.11 438.64 74.55 470.49 67.34 455.13 42.75 450.22 55.2 440.43 83.61 482.98 88.78 460.44 100.12 444.97 64.52 433.94 51.41 439.73 85.78 434.48 75.41 442.33 81.63 457.67 51.92 454.66 70.12 432.21 53.83 457.66 77.23 435.21 65.67 448.22 71.18 475.51 81.96 446.53 79.54 441.3 47.09 433.54 57.69 472.52 78.89 474.77 85.29 435.1 40.13 450.74 77.06 442.7 67.38 426.56 62.44 463.71 77.43 447.06 58.77 452.27 67.72 445.78 42.14 438.65 84.16 480.15 89.79 447.19 67.21 443.04 72.14 488.81 97.49 455.75 87.74 455.86 96.3 457.68 61.25 479.11 88.38 432.84 74.77 448.37 68.18 447.06 77.2 443.53 49.54 445.21 92.22 441.7 33.65 450.93 64.59 451.44 100.09 441.29 68.04 458.85 48.94 481.46 74.47 467.19 81.02 461.54 71.17 439.08 53.85 467.22 70.67 468.8 59.36 426.93 57.17 474.65 70.29 468.97 83.37 433.97 87.36 450.53 100.09 444.51 68.78 469.03 70.98 466.56 75.68 457.57 47.49 440.13 71.99 433.24 66.55 452.55 74.73 443.29 64.78 431.76 75.13 454.97 56.38 456.7 94.35 486.03 86.55 472.79 82.95 452.03 88.42 443.41 85.61 441.93 58.39 432.64 74.28 480.25 87.85 466.68 83.5 494.39 65.24 454.72 75.01 448.71 84.52 469.76 80.52 450.71 75.14 444.01 75.75 453.2 76.72 450.87 85.47 441.73 57.95 465.09 78.32 447.28 52.2 491.16 93.69 450.98 75.74 446.3 67.56 436.48 69.46 460.84 74.58 442.56 53.23 467.3 88.72 479.13 96.16 441.15 68.26 445.52 86.39 475.4 85.34 469.3 72.64 463.57 97.82 445.32 77.22 461.03 80.59 466.74 46.91 444.04 57.76 434.01 53.09 465.23 84.31 440.6 71.58 466.74 92.97 433.48 74.55 473.59 78.96 474.81 64.44 454.75 68.23 452.94 70.81 435.83 61.66 482.19 77.76 466.66 69.49 462.59 96.26 447.82 55.74 462.73 95.61 447.98 84.75 462.72 75.3 442.42 67.5 444.69 80.92 466.7 79.23 453.84 81.1 436.92 32.8 486.37 84.31 440.43 46.15 446.82 53.96 484.91 59.83 437.76 75.3 438.91 42.53 464.19 70.58 442.19 91.69 446.86 63.55 457.15 61.51 482.57 69.55 476.03 98.08 428.89 79.34 472.7 81.28 445.6 78.99 464.78 80.38 440.42 51.16 428.41 72.17 438.5 75.39 438.28 68.91 476.29 96.38 448.46 70.54 438.99 45.8 471.8 57.95 471.81 81.89 449.82 69.32 442.14 59.14 441.46 81.54 477.62 85.81 446.76 65.41 472.52 81.15 471.58 95.87 440.85 90.24 431.37 75.13 437.33 88.22 469.22 81.48 471.11 89.84 439.17 43.57 445.33 63.16 473.71 57.14 452.66 77.76 440.99 90.56 467.42 60.98 444.14 70.31 457.17 74.05 467.87 75.42 442.04 82.25 471.36 67.95 460.7 100.09 431.33 47.28 432.6 72.41 447.61 77.67 443.87 63.7 446.87 79.77 465.74 93.84 447.86 84.95 447.65 70.16 437.87 84.24 483.51 73.32 479.65 86.17 455.1

##Part 5: Data Preparation

The next step is to prepare the data for machine learning. Since all of this data is numeric and consistent this is a simple and straightforward task.

The goal is to use machine learning to determine a function that yields the output power as a function of a set of predictor features. The first step in building our ML pipeline is to convert the predictor features from DataFrame columns to Feature Vectors using the [pyspark.ml.feature.VectorAssembler()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.feature.VectorAssembler) method.

The VectorAssembler is a transformer that combines a given list of columns into a single vector column. It is useful for combining raw features and features generated by different feature transformers into a single feature vector, in order to train ML models like logistic regression and decision trees. VectorAssembler takes a list of input column names (each is a string) and the name of the output column (as a string).

### Exercise 5(a)

- Read the Spark documentation and useage examples for [VectorAssembler](https://spark.apache.org/docs/1.6.2/ml-features.html#vectorassembler).
- Convert the `plant_dataset` SQL table into a DataFrame.
- Set the vectorizer's input columns to a list of the four columns of the input DataFrame: `["AT", "V", "AP", "RH"]`.
- Set the vectorizer's output column name to `"features"`.

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code
from pyspark.ml.feature import VectorAssembler

datasetDF = sqlContext.table("plant_dataset")

vectorizer = VectorAssembler()
vectorizer.setInputCols(["AT","V","AP","RH"])
vectorizer.setOutputCol("features")

Out[18]: VectorAssembler_27b33c71f1b1

In [0]:
# TEST
Test.assertEquals(set(vectorizer.getInputCols()), {"AT", "V", "AP", "RH"}, "Incorrect vectorizer input columns")
Test.assertEquals(vectorizer.getOutputCol(), "features", "Incorrect vectorizer output column")

1 test passed.
1 test passed.


##Part 6: Data Modeling
Now let's model our data to predict what the power output will be given a set of sensor readings

Our first model will be based on simple linear regression since we saw some linear patterns in our data based on the scatter plots during the exploration stage.

We need a way of evaluating how well our linear regression model predicts power output as a function of input parameters. We can do this by splitting up our initial data set into a _Training Set_ used to train our model and a _Test Set_ used to evaluate the model's performance in giving predictions. We can use a DataFrame's [randomSplit()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrame.randomSplit) method to split our dataset. The method takes a list of weights and an optional random seed. The seed is used to initialize the random number generator used by the splitting function.

### Exercise 6(a)

Use the [randomSplit()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrame.randomSplit) method to divide up `datasetDF` into a testSetDF (15% of the input DataFrame) and a trainingSetDF (85% of the input DataFrame), and for reproducibility, use the seed 1900009193. Then cache each DataFrame in memory to maximize performance.

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code.
# We'll hold out 15% of our data for testing and leave 85% for training
(split15DF, split85DF) = datasetDF.randomSplit([0.15,0.85],1900009193)

# Let's cache these datasets for performance
testSetDF = split15DF.cache()
trainingSetDF = split85DF.cache()

In [0]:
# TEST
Test.assertEquals(trainingSetDF.count(), 40567, "Incorrect size for training data set")
Test.assertEquals(testSetDF.count(), 7273, "Incorrect size for test data set")

1 test passed.
1 test passed.


Next we'll create a Linear Regression Model and use the built in help to identify how to train it. See API details for [Linear Regression](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.LinearRegression) in the ML guide.

### Exercise 6(b)

- Read the documentation and examples for [Linear Regression](https://spark.apache.org/docs/1.6.2/ml-classification-regression.html#linear-regression)
- Run the next cell

In [0]:
# ***** LINEAR REGRESSION MODEL ****

from pyspark.ml.regression import LinearRegression
from pyspark.ml.regression import LinearRegressionModel
from pyspark.ml import Pipeline

# Let's initialize our linear regression learner
lr = LinearRegression()

# We use explain params to dump the parameters we can use
print(lr.explainParams())

aggregationDepth: suggested depth for treeAggregate (>= 2). (default: 2)
elasticNetParam: the ElasticNet mixing parameter, in range [0, 1]. For alpha = 0, the penalty is an L2 penalty. For alpha = 1, it is an L1 penalty. (default: 0.0)
epsilon: The shape parameter to control the amount of robustness. Must be > 1.0. Only valid when loss is huber (default: 1.35)
featuresCol: features column name. (default: features)
fitIntercept: whether to fit an intercept term. (default: True)
labelCol: label column name. (default: label)
loss: The loss function to be optimized. Supported options: squaredError, huber. (default: squaredError)
maxBlockSizeInMB: maximum memory in MB for stacking input data into blocks. Data is stacked within partitions. If more than remaining data size in a partition then it is adjusted to the data size. Default 0.0 represents choosing optimal value, depends on specific algorithm. Must be >= 0. (default: 0.0)
maxIter: max number of iterations (>= 0). (default: 100)
predic

The cell below is based on the [Spark ML Pipeline API for Linear Regression](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.LinearRegression).

The first step is to set the parameters for the method:
- Set the name of the prediction column to "Prediction_PE"
- Set the name of the label column to "PE"
- Set the maximum number of iterations to 100
- Set the regularization parameter to 0.15

Next, we create the [ML Pipeline](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.Pipeline) and set the stages to the Vectorizer and Linear Regression learner we created earlier.

Finally, we create a model by training on `trainingSetDF`.

### Exercise 6(c)

- Read the [Linear Regression](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.LinearRegression) documentation
- Run the next cell, and be sure you understand what's going on.

In [0]:
# Now we set the parameters for the method
lr.setPredictionCol("Prediction_PE")\
  .setLabelCol("PE")\
  .setMaxIter(100)\
  .setRegParam(0.15)


# We will use the new spark.ml pipeline API. If you have worked with scikit-learn this will be very familiar.
lrPipeline = Pipeline()

lrPipeline.setStages([vectorizer, lr])

# Let's first train on the entire dataset to see what we get
lrModel = lrPipeline.fit(trainingSetDF)

From the Wikipedia article on [Linear Regression](https://en.wikipedia.org/wiki/Linear_regression):
> In statistics, linear regression is an approach for modeling the relationship between a scalar dependent variable \\( y \\) and one or more explanatory variables (or independent variables) denoted \\(X\\). In linear regression, the relationships are modeled using linear predictor functions whose unknown model parameters are estimated from the data. Such models are called linear models.

Linear regression has many practical uses. Most applications fall into one of the following two broad categories:
  - If the goal is prediction, or forecasting, or error reduction, linear regression can be used to fit a predictive model to an observed data set of \\(y\\) and \\(X\\) values. After developing such a model, if an additional value of \\(X\\) is then given without its accompanying value of \\(y\\), the fitted model can be used to make a prediction of the value of \\(y\\).
  - Given a variable \\(y\\) and a number of variables \\( X_1 \\), ..., \\( X_p \\) that may be related to \\(y\\), linear regression analysis can be applied to quantify the strength of the relationship between \\(y\\) and the \\( X_j\\), to assess which \\( X_j \\) may have no relationship with \\(y\\) at all, and to identify which subsets of the \\( X_j \\) contain redundant information about \\(y\\).

We are interested in both uses, as we would like to predict power output as a function of the input variables, and we would like to know which input variables are weakly or strongly correlated with power output.

Since Linear Regression is simply a Line of best fit over the data that minimizes the square of the error, given multiple input dimensions we can express each predictor as a line function of the form:

\\[ y = a + b x_1 + b x_2 + b x_i ... \\]

where \\(a\\) is the intercept and the \\(b\\) are the coefficients.

To express the coefficients of that line we can retrieve the Estimator stage from the PipelineModel and express the weights and the intercept for the function.

### Exercise 6(d)

Run the next cell. Ensure that you understand what's going on.

In [0]:
# The intercept is as follows:
intercept = lrModel.stages[1].intercept

# The coefficients (i.e., weights) are as follows:
weights = lrModel.stages[1].coefficients

# Create a list of the column names (without PE)
featuresNoLabel = [col for col in datasetDF.columns if col != "PE"]

# Merge the weights and labels
coefficients = list(zip(weights, featuresNoLabel))

# Now let's sort the coefficients from greatest absolute weight most to the least absolute weight
coefficients = sorted(coefficients, key=lambda tup: abs(tup[0]), reverse=True)

equation = "y = {intercept}".format(intercept=intercept)
variables = []
for x in coefficients:
    weight = abs(x[0])
    name = x[1]
    symbol = "+" if (x[0] > 0) else "-"
    equation += (" {} ({} * {})".format(symbol, weight, name))

# Finally here is our equation
print("Linear Regression Equation: " + equation)

Linear Regression Equation: y = 427.46130332395563 - (1.8898788266271183 * AT) - (0.2656593345796064 * V) - (0.1423825895083631 * RH) + (0.08775575891840728 * AP)


Recall **Part 4: Visualize Your Data** when we visualized each predictor against Power Output using a Scatter Plot, does the final equation seems logical given those visualizations?

### Exercise 6(e)

Now let's see what our predictions look like given this model. We apply our Linear Regression model to the 15% of the data that we split from the input dataset. The output of the model will be a predicted Power Output column named "Prediction_PE".

- Run the next cell
- Scroll through the resulting table and notice how the values in the Power Output (PE) column compare to the corresponding values in the predicted Power Output (Prediction_PE) column

In [0]:
# Apply our LR model to the test data and predict power output
resultsDF = lrModel.transform(testSetDF).select("AT", "V", "AP", "RH", "PE", "Prediction_PE")

display(resultsDF)

AT V AP RH PE Prediction_PE 2.58 39.42 1028.68 69.03 488.69 492.5570489125545 2.64 39.64 1011.02 85.24 481.29 488.5274226509197 2.8 39.64 1011.01 82.96 482.66 488.54879678514925 3.21 38.44 1017.11 84.86 492.93 488.3575208770641 3.69 38.44 1016.74 82.87 490.78 487.7012507626049 3.94 39.9 1008.06 97.49 488.81 483.9975649814378 3.95 35.47 1017.36 84.88 488.64 487.7671100570009 3.95 38.44 1016.75 79.65 492.46 487.6692317634879 3.99 39.64 1011.53 83.58 492.06 486.25719677060533 3.99 39.9 1009.74 96.81 490.91 484.1473208759551 4.49 38.44 1015.47 76.96 485.78 486.9193789914712 4.73 41.31 999.77 93.44 486.6 481.9791352927204 4.89 45.87 1007.58 99.35 482.69 480.30923948793543 5.01 39.4 1003.69 91.9 475.34 482.5206503131149 5.04 40.64 1021.35 93.63 484.42 483.437981196087 5.15 40.07 1012.27 63.31 495.35 486.9017381687828 5.21 35.79 1012.44 94.35 485.17 483.52073029186244 5.23 40.78 1025.13 92.74 483.12 483.50014918556076 5.35 35.57 1027.12 80.81 488.65 486.5307071126076 5.41 40.07 1019.16 64.77 495.24 486.8071282721254 5.65 40.72 1022.46 85.17 487.09 483.5658679647183 5.67 45.87 1008.91 93.29 478.44 479.81468765494844 5.74 37.8 1021.37 74.47 490.81 485.5993440578127 5.74 40.62 1016.31 84.91 481.15 482.91966635970374 5.79 39.61 1021.64 85.41 489.6 483.4900352465787 5.81 35.79 1012.14 92.28 484.41 482.65520822849294 5.82 41.38 1021.06 86.91 492.12 482.6986496351388 5.84 40.62 1018.58 82.73 482.1 483.24027809491406 5.98 41.31 1001.66 89.5 484.51 480.3436325464553 6.01 35.79 1011.26 90.72 482.79 482.4221242349524 6.03 40.78 1025.53 98.68 480.36 481.1775958461467 6.06 41.17 1019.67 84.7 489.62 482.4935521949269 6.07 38.91 1019.25 83.39 483.56 483.22470727632077 6.1 43.65 1018.07 75.85 485.24 482.87879859498395 6.13 39.48 1005.17 53.5 484.12 485.9801032408466 6.13 40.81 1026.31 91.66 483.8 482.04861345375167 6.28 41.06 1020.96 90.91 489.79 481.3360104280305 6.31 42.07 1004.61 77.74 483.27 481.4513701808155 6.43 36.08 1022.73 85.03 486.39 483.3680494098376 6.45 40.02 1032.08 79.7 481.36 483.8629696030281 6.49 39.33 1010.85 91.85 489.22 480.37767616645857 6.64 35.19 1019.83 76.01 484.03 484.23741092052387 6.64 39.04 1018.84 74.94 481.53 483.2800936518371 6.65 40.77 1021.79 88.84 482.9 481.08136570939115 6.67 39.37 1020.31 73.56 488.13 483.4612186457586 6.72 39.85 1011.84 84.66 489.09 480.9154702022473 6.76 37.49 1011.66 80.91 484.85 481.98496975284115 6.76 39.22 1013.91 77.0 487.08 482.2795454865625 6.76 40.62 1015.67 87.16 478.56 480.6154654444425 6.84 39.4 1011.9 93.75 484.09 479.51923905051694 6.86 40.02 1031.5 77.94 476.45 483.2878143014731 6.86 41.17 1020.12 79.14 490.23 481.812786422805 6.86 41.38 1021.35 90.78 487.49 480.2076042041356 6.87 39.85 1012.66 83.34 486.26 480.89189311871735 6.89 43.65 1019.87 72.77 484.0 481.9822930636874 6.94 39.61 1017.74 81.43 480.07 481.541109842419 6.99 35.19 1019.32 68.95 480.05 484.536418976085 7.0 35.77 1018.21 64.84 482.8 484.8512213242425 7.04 39.37 1019.37 69.11 488.0 483.3130755898355 7.06 41.38 1021.94 83.55 487.71 480.91083045871744 7.06 41.74 1021.95 90.38 448.97 479.8435975695159 7.09 43.13 1017.91 92.37 485.04 478.7797601104994 7.17 39.4 1011.48 90.38 484.33 479.33855094562745 7.19 39.4 1011.45 90.65 483.04 479.2596773971601 7.19 41.39 1018.12 90.76 486.35 479.30068414848654 7.2 40.35 1011.83 95.59 484.9 478.3183794372609 7.28 40.67 1020.16 72.7 493.3 482.072321089702 7.3 39.72 1020.85 77.83 485.1 481.61702867049587 7.32 39.42 1026.15 76.51 476.12 482.3119794347558 7.32 41.26 1010.11 95.18 482.1 477.75728093995696 7.35 41.66 1015.55 79.67 485.35 480.28006613311715 7.38 44.71 1020.27 70.55 486.91 481.1258451962617 7.39 39.81 1019.45 85.02 482.99 480.27644135493637 7.49 39.81 1018.2 85.96 483.71 479.8439191394878 7.5 40.02 1031.39 82.53 476.01 481.41510263310727 7.51 41.66 1015.9 78.31 485.58 480.2020403582096 7.53 41.16 1023.19 91.28 475.7 479.0901097455586 7.55 41.04 1027.03 83.32 476.58 480.55453881590887 7.61 39.37 1015.84 83.73 483.74 479.8444333710638 7.62 44.71 1020.56 69.96 486.07 480.78

From a visual inspection of the predictions, we can see that they are close to the actual values.

However, we would like a scientific measure of how well the Linear Regression model is performing in accurately predicting values. To perform this measurement, we can use an evaluation metric such as [Root Mean Squared Error](https://en.wikipedia.org/wiki/Root-mean-square_deviation) (RMSE) to validate our Linear Regression model.

RSME is defined as follows: \\( RMSE = \sqrt{\frac{\sum_{i = 1}^{n} (x_i - y_i)^2}{n}}\\) where \\(y_i\\) is the observed value and \\(x_i\\) is the predicted value

RMSE is a frequently used measure of the differences between values predicted by a model or an estimator and the values actually observed. The lower the RMSE, the better our model.

Spark ML Pipeline provides several regression analysis metrics, including [RegressionEvaluator()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.evaluation.RegressionEvaluator).

After we create an instance of [RegressionEvaluator](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.evaluation.RegressionEvaluator), we set the label column name to "PE" and set the prediction column name to "Predicted_PE". We then invoke the evaluator on the predictions.

### Exercise 6(f)

Run the next cell and ensure that you understand what's going on.

In [0]:
# Now let's compute an evaluation metric for our test dataset
from pyspark.ml.evaluation import RegressionEvaluator

# Create an RMSE evaluator using the label and predicted columns
regEval = RegressionEvaluator(predictionCol="Prediction_PE", labelCol="PE", metricName="rmse")

# Run the evaluator on the DataFrame
rmse = regEval.evaluate(resultsDF)

print("Root Mean Squared Error: %.2f" % rmse)

Root Mean Squared Error: 4.56


Another useful statistical evaluation metric is the coefficient of determination, denoted \\(R^2\\) or \\(r^2\\) and pronounced "R squared". It is a number that indicates the proportion of the variance in the dependent variable that is predictable from the independent variable and it provides a measure of how well observed outcomes are replicated by the model, based on the proportion of total variation of outcomes explained by the model. The coefficient of determination ranges from 0 to 1 (closer to 1), and the higher the value, the better our model.

To compute \\(r^2\\), we invoke the evaluator with  `regEval.metricName: "r2"`

### Exercise 6(g)

Run the next cell and ensure that you understand what's going on.

In [0]:
# Now let's compute another evaluation metric for our test dataset
r2 = regEval.evaluate(resultsDF, {regEval.metricName: "r2"})

print("r2: {0:.2f}".format(r2))

r2: 0.93


Generally, assuming a Gaussian distribution of errors, a good model will have 68% of predictions within 1 RMSE and 95% within 2 RMSE of the actual value (see http://statweb.stanford.edu/~susan/courses/s60/split/node60.html).

Let's examine the predictions and see if a RMSE of 4.60 meets this criteria.

We create a new DataFrame using [selectExpr()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrame.selectExpr) to project a set of SQL expressions, and register the DataFrame as a SQL table using [registerTempTable()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.sql.html#pyspark.sql.DataFrame.registerTempTable).

### Exercise 6(h)

Run the next cell and ensure that you understand what's going on.

In [0]:
# First we remove the table if it already exists
sqlContext.sql("DROP TABLE IF EXISTS Plant_RMSE_Evaluation")
dbutils.fs.rm("dbfs:/user/hive/warehouse/Plant_RMSE_Evaluation", True)

# Next we calculate the residual error and divide it by the RMSE
resultsDF.selectExpr("PE", "Prediction_PE", "PE - Prediction_PE Residual_Error", "(PE - Prediction_PE) / {} Within_RSME".format(rmse)).registerTempTable("Plant_RMSE_Evaluation")

We can use SQL to explore the `Plant_RMSE_Evaluation` table. First let's look at at the table using a SQL SELECT statement.

### Exercise 6(i)

Run the next cell and ensure that you understand what's going on.

In [0]:
%sql
SELECT * from Plant_RMSE_Evaluation

PE Prediction_PE Residual_Error Within_RSME 488.69 492.5570489125545 -3.8670489125544805 -0.8479657008019647 481.29 488.5274226509197 -7.237422650919655 -1.587020570198344 482.66 488.54879678514925 -5.888796785149225 -1.2912941640298088 492.93 488.3575208770641 4.572479122935931 1.0026522941809557 490.78 487.7012507626049 3.0787492373950727 0.6751075080032226 488.81 483.9975649814378 4.812435018562212 1.0552697742794663 488.64 487.7671100570009 0.8728899429991088 0.1914071295646686 492.46 487.6692317634879 4.790768236512065 1.0505186867083653 492.06 486.25719677060533 5.802803229394669 1.2724375145746831 490.91 484.1473208759551 6.762679124044951 1.4829189059652998 485.78 486.9193789914712 -1.139378991471233 -0.24984279403482415 486.6 481.9791352927204 4.6208647072796225 1.0132622752969194 482.69 480.30923948793543 2.380760512064569 0.5220526819560974 475.34 482.5206503131149 -7.180650313114938 -1.5745715434853766 484.42 483.437981196087 0.9820188039130358 0.21533688404027726 495.35 486.9017381687828 8.448261831217224 1.8525331399375402 485.17 483.52073029186244 1.649269708137581 0.36165152691293573 483.12 483.50014918556076 -0.3801491855607537 -0.0833590362658179 488.65 486.5307071126076 2.119292887392362 0.4647181142777866 495.24 486.8071282721254 8.432871727874613 1.849158401199697 487.09 483.5658679647183 3.5241320352816956 0.7727709575419538 478.44 479.81468765494844 -1.3746876549484455 -0.3014412300107531 490.81 485.5993440578127 5.210655942187316 1.1425915776007243 481.15 482.91966635970374 -1.7696663597037627 -0.3880520802361901 489.6 483.4900352465787 6.109964753421309 1.3397918312307386 484.41 482.65520822849294 1.7547917715070867 0.38479038355493367 492.12 482.6986496351388 9.421350364861212 2.0659117961254467 482.1 483.24027809491406 -1.1402780949140379 -0.2500399492553067 484.51 480.3436325464553 4.166367453544694 0.9136002097293747 482.79 482.4221242349524 0.36787576504764274 0.08066772310635688 480.36 481.1775958461467 -0.8175958461466735 -0.17928225122773692 489.62 482.4935521949269 7.126447805073099 1.5626860285213156 483.56 483.22470727632077 0.33529272367923113 0.0735229204071913 485.24 482.87879859498395 2.361201405016061 0.517763764931644 484.12 485.9801032408466 -1.8601032408465699 -0.40788306118076434 483.8 482.04861345375167 1.751386546248341 0.3840436864512207 489.79 481.3360104280305 8.453989571969544 1.8537891177673744 483.27 481.4513701808155 1.8186298191844799 0.39878877769493215 486.39 483.3680494098376 3.021950590162362 0.6626527121642236 481.36 483.8629696030281 -2.5029696030280775 -0.548850666622598 489.22 480.37767616645857 8.842323833541457 1.9389429758399161 484.03 484.23741092052387 -0.2074109205238983 -0.04548102456243504 481.53 483.2800936518371 -1.750093651837119 -0.38376018082709595 482.9 481.08136570939115 1.818634290608827 0.3987897581879556 488.13 483.4612186457586 4.668781354241389 1.0237694279189362 489.09 480.9154702022473 8.174529797752655 1.7925092351880656 484.85 481.98496975284115 2.8650302471588702 0.6282432511943745 487.08 482.2795454865625 4.800454513437501 1.052642691546932 478.56 480.6154654444425 -2.055465444442518 -0.45072204554029316 484.09 479.51923905051694 4.570760949483031 1.0022755334548739 476.45 483.2878143014731 -6.837814301473088 -1.499394532424507 490.23 481.812786422805 8.417213577195014 1.8457248850961943 487.49 480.2076042041356 7.282395795864431 1.5968822722954024 486.26 480.89189311871735 5.3681068812826425 1.1771173875739165 484.0 481.9822930636874 2.0177069363126066 0.442442367539927 480.07 481.541109842419 -1.4711098424190254 -0.32258466771227895 480.05 484.536418976085 -4.486418976084963 -0.983781042643722 482.8 484.8512213242425 -2.0512213242424764 -0.4497913957240903 488.0 483.3130755898355 4.686924410164522 1.0277478335399777 487.71 480.91083045871744 6.799169541282538 1.4909205172521318 448.97 479.8435975695159 -30.87359756951588 -6.7699562098423645 485.04 478.7797601104994 6.26023988950061 1.3727441325747676 484.33 479.33855094562745 4.991449054

Now we can display the RMSE as a Histogram.

### Exercise 6(j)

Perform the following steps:

- Run the following cell
- Click on the drop down next to the "Bar chart" icon a select "Histogram" to turn the table into a Histogram plot

<img src="http://spark-mooc.github.io/web-assets/images/cs110x/change-plot-type-histogram.png" style="border: 1px solid #999999"/>


- Click on "Plot Options..."
- In the "All Fields:" box, click on "&lt;id&gt;" and drag it into the "Keys:" box
- Change the "Aggregation" to "COUNT"

<img src="http://spark-mooc.github.io/web-assets/images/cs110x/customize-plot-histogram.png" style="border: 1px solid #999999"/>

- Apply your changes by clicking the Apply button
- Increase the size of the graph by clicking and dragging the size control

Notice that the histogram clearly shows that the RMSE is centered around 0 with the vast majority of the error within 2 RMSEs.

In [0]:
%sql
-- Now we can display the RMSE as a Histogram
SELECT Within_RSME from Plant_RMSE_Evaluation

Within_RSME -0.8479657008019647 -1.587020570198344 -1.2912941640298088 1.0026522941809557 0.6751075080032226 1.0552697742794663 0.1914071295646686 1.0505186867083653 1.2724375145746831 1.4829189059652998 -0.24984279403482415 1.0132622752969194 0.5220526819560974 -1.5745715434853766 0.21533688404027726 1.8525331399375402 0.36165152691293573 -0.0833590362658179 0.4647181142777866 1.849158401199697 0.7727709575419538 -0.3014412300107531 1.1425915776007243 -0.3880520802361901 1.3397918312307386 0.38479038355493367 2.0659117961254467 -0.2500399492553067 0.9136002097293747 0.08066772310635688 -0.17928225122773692 1.5626860285213156 0.0735229204071913 0.517763764931644 -0.40788306118076434 0.3840436864512207 1.8537891177673744 0.39878877769493215 0.6626527121642236 -0.548850666622598 1.9389429758399161 -0.04548102456243504 -0.38376018082709595 0.3987897581879556 1.0237694279189362 1.7925092351880656 0.6282432511943745 1.052642691546932 -0.45072204554029316 1.0022755334548739 -1.499394532424507 1.8457248850961943 1.5968822722954024 1.1771173875739165 0.442442367539927 -0.32258466771227895 -0.983781042643722 -0.4497913957240903 1.0277478335399777 1.4909205172521318 -6.7699562098423645 1.3727441325747676 1.0945239357245091 0.8289483732071898 1.5457725493972052 1.4432164213844934 2.4620031530093 0.7637452463318255 -1.35777599391047 0.9522705542151809 1.1117340694847975 1.2683482915810966 0.5950285890251727 0.8477534265465744 -1.185229808526448 1.1792778988986232 -0.7433825770487158 -0.8715360649965164 0.8542190598630265 1.159610953185158 0.7552113185236745 -0.7349846018014464 1.4237186858040276 -0.14835198301496222 -0.31090155396888236 0.5014274614921912 0.6234851278909229 0.04692494513723176 0.14444423234422663 -0.7377275556768425 0.6898157840543394 1.7277077413599038 1.9102319639095753 -1.3040340688295848 1.2738356260489836 0.11215181592972048 0.8606261074341274 1.6024767026571212 0.8668242132338824 0.031192333442396407 -0.7912625378192079 0.4658839370829538 0.5927996326904091 -0.6189656407606264 0.05123964563356482 1.0302963833274619 1.2384899999064936 1.3409223124209828 1.3363671887377206 -0.6821310570710802 1.8524220597418168 0.3136580880115832 -0.17034479053043772 -0.3584737665937475 1.6680297772867931 -0.4033038716027747 1.614740935865506 1.3471820500758163 1.3804463909308577 0.12777157107160508 1.482590499505431 1.3032312668874908 -0.009345432481513127 1.5740440904799256 1.022709823848927 0.41311274000881704 -0.10508496166332959 -0.8200187795254046 0.10244096669610069 -0.9404761262829975 -1.4994320310182845 0.8540432690936229 -0.41254196648426483 0.9736740171208719 1.361732664663335 0.7545709915114485 -1.3995962574563408 1.922662754565376 -0.7016918100036168 0.07102560872254814 -1.5295825682909872 0.9080885911715222 -1.115044717334256 -1.0778850405879208 0.2649728325180493 -0.11105980273183659 -0.7175905538204536 -0.707591057961189 -1.781048627521426 0.13733526977851807 0.9447438222372928 1.4076604137667943 -1.3059565327547389 1.5638407451544578 1.0027040415273327 -0.47442567430276683 0.8032954586645074 -3.9092343638534546 0.7683398940399296 1.4385867977487663 0.7699312848313685 0.43385533782303415 1.4282785950013523 -1.166120448923354 0.03794267963595728 0.1653123827976901 -0.4226831290801073 -0.5674198002930692 0.3288024407125543 0.1408205882024034 -0.111079468013492 0.17042495858232068 1.1962472024108912 -0.4922657938660634 0.5557891604847619 1.8455016487437172 0.5242047025874543 1.0743046556909794 0.3234984882829211 1.34081507085127 -0.8437414268725737 1.4870290661055194 1.51864275318786 1.334174783940398 0.018592609895377886 -0.878497716340202 0.24192755089127216 0.7176001473042656 -0.4458909935381612 -0.9270461247012401 1.7382172056969591 0.920895515082737 -1.5377230113681706 -1.3931590686597115 1.1660796393708848 1.2630721786366605 -0.11255954194607418 -1.9872335273666424 -0.6198136393379989 1.1733799090593175 1.234497709141741 -0.21969363969561667 1.334961437332059 -1.498447010603012 -0.0901007338024578 1.490151584957281 

Using a complex SQL SELECT statement, we can count the number of predictions within + or - 1.0 and + or - 2.0 and then display the results as a pie chart.

### Exercise 6(k)

Perform the following steps:

  - Run the following cell
  - Click on the drop down next to the "Bar chart" icon a select "Pie" to turn the table into a Pie Chart plot
  - Increase the size of the graph by clicking and dragging the size control

In [0]:
%sql
SELECT case 
       when Within_RSME <= 1.0 AND Within_RSME >= -1.0 then 1
       when Within_RSME <= 2.0 AND Within_RSME >= -2.0 then 2 
       else 3
       end RSME_Multiple, COUNT(*) AS count
FROM Plant_RMSE_Evaluation
GROUP BY RSME_Multiple

RSME_Multiple count 1 4939 3 213 2 2121

From the pie chart, we can see that 68% of our test data predictions are within 1 RMSE of the actual values, and 97% (68% + 29%) of our test data predictions are within 2 RMSE. So the model is pretty decent. Let's see if we can tune the model to improve it further.

##Part 7: Tuning and Evaluation

Now that we have a model with all of the data let's try to make a better model by tuning over several parameters. The process of tuning a model is known as [Model Selection](https://spark.apache.org/docs/1.6.2/ml-tuning.html#model-selection-aka-hyperparameter-tuning) or [Hyperparameter Tuning](https://spark.apache.org/docs/1.6.2/ml-tuning.html#model-selection-aka-hyperparameter-tuning), and Spark ML Pipeline makes the tuning process very simple and easy.

An important task in ML is model selection, or using data to find the best model or parameters for a given task. This is also called tuning. Tuning may be done for individual Estimators such as [LinearRegression](https://spark.apache.org/docs/1.6.2/ml-classification-regression.html#linear-regression), or for entire Pipelines which include multiple algorithms, featurization, and other steps. Users can tune an entire Pipeline at once, rather than tuning each element in the Pipeline separately.

Spark ML Pipeline supports model selection using tools such as [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation), which requires the following items:
  - [Estimator](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.Estimator): algorithm or Pipeline to tune
  - [Set of ParamMaps](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.tuning.ParamGridBuilder): parameters to choose from, sometimes called a _parameter grid_ to search over
  - [Evaluator](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.evaluation.Evaluator): metric to measure how well a fitted Model does on held-out test data

At a high level, model selection tools such as [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) work as follows:
  - They split the input data into separate training and test datasets.
  - For each (training, test) pair, they iterate through the set of ParamMaps:
    - For each [ParamMap](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.tuning.ParamGridBuilder), they fit the [Estimator](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.Estimator) using those parameters, get the fitted Model, and evaluate the Model's performance using the [Evaluator](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.evaluation.Evaluator).
  - They select the Model produced by the best-performing set of parameters.

The [Evaluator](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.evaluation.Evaluator) can be a [RegressionEvaluator](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.evaluation.RegressionEvaluator) for regression problems. To help construct the parameter grid, users can use the [ParamGridBuilder](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.tuning.ParamGridBuilder) utility.

Note that cross-validation over a grid of parameters is expensive. For example, in the next cell, the parameter grid has 10 values for [lr.regParam](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.LinearRegression.regParam), and [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) uses 3 folds. This multiplies out to (10 x 3) = 30 different models being trained. In realistic settings, it can be common to try many more parameters (e.g., multiple values for multiple parameters) and use more folds (_k_ = 3 and _k_ = 10 are common). In other words, using [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) can be very expensive. However, it is also a well-established method for choosing parameters which is more statistically sound than heuristic hand-tuning.

We perform the following steps:
  - Create a [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) using the Pipeline and [RegressionEvaluator](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.evaluation.RegressionEvaluator) that we created earlier, and set the number of folds to 3
  - Create a list of 10 regularization parameters
  - Use [ParamGridBuilder](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.tuning.ParamGridBuilder) to build a parameter grid with the regularization parameters and add the grid to the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation)
  - Run the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) to find the parameters that yield the best model (i.e., lowest RMSE) and return the best model.

### Exercise 7(a)

Run the next cell. _Note that it will take some time to run the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) as it will run almost 200 Spark jobs_

In [0]:
from pyspark.ml.tuning import ParamGridBuilder, CrossValidator

# We can reuse the RegressionEvaluator, regEval, to judge the model based on the best Root Mean Squared Error
# Let's create our CrossValidator with 3 fold cross validation
crossval = CrossValidator(estimator=lrPipeline, evaluator=regEval, numFolds=3)

# Let's tune over our regularization parameter from 0.05 to 0.50
regParam = [x / 200.0 for x in range(1, 11)]

# We'll create a paramter grid using the ParamGridBuilder, and add the grid to the CrossValidator
paramGrid = (ParamGridBuilder()
             .addGrid(lr.regParam, regParam)
             .build())
crossval.setEstimatorParamMaps(paramGrid)

# Now let's find and return the best model
cvModel = crossval.fit(trainingSetDF).bestModel

/databricks/spark/python/pyspark/ml/util.py:886: UserWarning: Cannot find mlflow module. To enable MLflow logging, install mlflow from PyPI.
  warnings.warn(_MLflowInstrumentation._NO_MLFLOW_WARNING)


Now that we have tuned our Linear Regression model, let's see what the new RMSE and \\(r^2\\) values are versus our intial model.

### Exercise 7(b)

Complete and run the next cell.

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code.
# Now let's use cvModel to compute an evaluation metric for our test dataset: testSetDF
resultsDF = cvModel.transform(testSetDF)

# Run the previously created RMSE evaluator, regEval, on the resultsDF DataFrame
rmseNew = regEval.evaluate(resultsDF)

# Now let's compute the r2 evaluation metric for our test dataset
r2New = regEval.evaluate(resultsDF, {regEval.metricName: 'r2'})

print("Original Root Mean Squared Error: {0:2.2f}".format(rmse))
print("New Root Mean Squared Error: {0:2.2f}".format(rmseNew))
print("Old r2: {0:2.2f}".format(r2))
print("New r2: {0:2.2f}".format(r2New))

Original Root Mean Squared Error: 4.56
New Root Mean Squared Error: 4.55
Old r2: 0.93
New r2: 0.93


In [0]:
# TEST
Test.assertEquals(round(rmse, 2), 4.56, "Incorrect value for rmse")
Test.assertEquals(round(rmseNew, 2), 4.55, "Incorrect value for rmseNew")
Test.assertEquals(round(r2, 2), 0.93, "Incorrect value for r2")
Test.assertEquals(round(r2New, 2), 0.93, "Incorrect value for r2New")

1 test passed.
1 test passed.
1 test passed.
1 test passed.


So tuned linear regression model improves a little bit over our initial model. Let's look at the regularization parameter that the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) has selected.

Recall that the orginal regularization parameter we used was 0.015.

**NOTE**: The ML Python API currently doesn't provide a way to query the regularization parameter, so we cheat, by "reaching through" to the JVM version of the API.

In [0]:
print("Regularization parameter of the best model: {0:.2f}".format(cvModel.stages[-1]._java_obj.parent().getRegParam()))

Regularization parameter of the best model: 0.01


Given that the only linearly correlated variable is Temperature, it makes sense try another Machine Learning method such as [Decision Tree](https://en.wikipedia.org/wiki/Decision_tree_learning) to handle non-linear data and see if we can improve our model.

[Decision Tree Learning](https://en.wikipedia.org/wiki/Decision_tree_learning) uses a [Decision Tree](https://en.wikipedia.org/wiki/Decision_tree) as a predictive model which maps observations about an item to conclusions about the item's target value. It is one of the predictive modelling approaches used in statistics, data mining and machine learning. Decision trees where the target variable can take continuous values (typically real numbers) are called regression trees.

Spark ML Pipeline provides [DecisionTreeRegressor()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.DecisionTreeRegressor) as an implementation of [Decision Tree Learning](https://en.wikipedia.org/wiki/Decision_tree_learning).

The cell below is based on the [Spark ML Pipeline API for Decision Tree Regressor](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.DecisionTreeRegressor).

### Exercise 7(c)

- Read the [Decision Tree Regressor](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.DecisionTreeRegressor) documentation
- In the next cell, create a [DecisionTreeRegressor()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.DecisionTreeRegressor)

- The next step is to set the parameters for the method (we do this for you):
  - Set the name of the prediction column to "Prediction_PE"
  - Set the name of the label column to "PE"
  - Set the name of the features column to "features"
  - Set the maximum number of bins to 100

- Create the [ML Pipeline](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.Pipeline) and set the stages to the Vectorizer we created earlier and [DecisionTreeRegressor()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.DecisionTreeRegressor) learner we just created.

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code.
from pyspark.ml.regression import DecisionTreeRegressor

# Create a DecisionTreeRegressor
dt = DecisionTreeRegressor()

dt.setLabelCol("PE")\
  .setPredictionCol("Prediction_PE")\
  .setFeaturesCol("features")\
  .setMaxBins(100)

# Create a Pipeline
dtPipeline = Pipeline()

# Set the stages of the Pipeline
dtPipeline.setStages([vectorizer,dt])

Out[33]: Pipeline_7917f2360f06

In [0]:
# TEST
Test.assertEqualsHashed(str(dtPipeline.getStages()[0].__class__.__name__), '4617be70bcf475326c0b07400b97b13457cc4949', "Incorrect pipeline stage 0")
Test.assertEqualsHashed(str(dtPipeline.getStages()[1].__class__.__name__), '46b18f257cf2f778d0d3b6e30ccc7b3398d7846a', "Incorrect pipeline stage 1")

1 test passed.
1 test passed.


Instead guessing what parameters to use, we will use [Model Selection](https://spark.apache.org/docs/1.6.2/ml-tuning.html#model-selection-aka-hyperparameter-tuning) or [Hyperparameter Tuning](https://spark.apache.org/docs/1.6.2/ml-tuning.html#model-selection-aka-hyperparameter-tuning) to create the best model.

We can reuse the exiting [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) by replacing the Estimator with our new `dtPipeline` (the number of folds remains 3).

### Exercise 7(d)

- Use [ParamGridBuilder](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.tuning.ParamGridBuilder) to build a parameter grid with the parameter `dt.maxDepth` and a list of the values 2 and 3, and add the grid to the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation)
- Run the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) to find the parameters that yield the best model (i.e., lowest RMSE) and return the best model.

_Note that it will take some time to run the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) as it will run almost 50 Spark jobs_

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code.
# Let's just reuse our CrossValidator with the new dtPipeline, RegressionEvaluator regEval, and 3 fold cross validation
crossval.setEstimator(dtPipeline)

# Let's tune over our dt.maxDepth parameter on the values 2 and 3, create a paramter grid using the ParamGridBuilder
paramGrid = (ParamGridBuilder()
             .addGrid(dt.maxDepth,(2,3))
             .build())

# Add the grid to the CrossValidator
crossval.setEstimatorParamMaps(paramGrid)

# Now let's find and return the best model
dtModel = crossval.fit(trainingSetDF).bestModel

In [0]:
# TEST
Test.assertEqualsHashed(str(dtModel.stages[0].__class__.__name__), '4617be70bcf475326c0b07400b97b13457cc4949', "Incorrect pipeline stage 0")
Test.assertEqualsHashed(str(dtModel.stages[1].__class__.__name__), 'a2bf7b0c1a0fb9ad35650d0478ad51a9b880befa', "Incorrect pipeline stage 1")

1 test passed.
1 test passed.


### Exercise 7(e)

Now let's see how our tuned DecisionTreeRegressor model's RMSE and \\(r^2\\) values compare to our tuned LinearRegression model.

Complete and run the next cell.

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code.

# Now let's use dtModel to compute an evaluation metric for our test dataset: testSetDF
resultsDF = dtModel.transform(testSetDF)

# Run the previously created RMSE evaluator, regEval, on the resultsDF DataFrame
rmseDT = regEval.evaluate(resultsDF)

# Now let's compute the r2 evaluation metric for our test dataset
r2DT = regEval.evaluate(resultsDF, {regEval.metricName: "r2"})

print("LR Root Mean Squared Error: {0:.2f}".format(rmseNew))
print("DT Root Mean Squared Error: {0:.2f}".format(rmseDT))
print("LR r2: {0:.2f}".format(r2New))
print("DT r2: {0:.2f}".format(r2DT))

LR Root Mean Squared Error: 4.55
DT Root Mean Squared Error: 5.07
LR r2: 0.93
DT r2: 0.91


In [0]:
# TEST
Test.assertEquals(round(rmseDT, 2), 5.07, "Incorrect value for rmseDT")
Test.assertEquals(round(r2DT, 2), 0.91, "Incorrect value for r2DT")

1 test passed.
1 test passed.


The line below will pull the Decision Tree model from the Pipeline as display it as an if-then-else string. Again, we have to "reach through" to the JVM API to make this one work.

**TODO**: Run the next cell

In [0]:
print(dtModel.stages[-1]._java_obj.toDebugString())

DecisionTreeRegressionModel: uid=DecisionTreeRegressor_adf0a94c7ddd, depth=3, numNodes=15, numFeatures=4
  If (feature 0 <= 17.755000000000003)
   If (feature 0 <= 11.735)
    If (feature 0 <= 8.614999999999998)
     Predict: 483.88400805951636
    Else (feature 0 > 8.614999999999998)
     Predict: 476.25130722038693
   Else (feature 0 > 11.735)
    If (feature 0 <= 14.545)
     Predict: 468.7150327349525
    Else (feature 0 > 14.545)
     Predict: 462.0213858939801
  Else (feature 0 > 17.755000000000003)
   If (feature 0 <= 22.905)
    If (feature 1 <= 45.935)
     Predict: 458.16589142091146
    Else (feature 1 > 45.935)
     Predict: 449.0612781602
   Else (feature 0 > 22.905)
    If (feature 1 <= 66.21000000000001)
     Predict: 442.8916497960417
    Else (feature 1 > 66.21000000000001)
     Predict: 434.7378667799852



So our DecisionTree has slightly worse RMSE than our LinearRegression model (LR: 4.55 vs DT: 5.07). Maybe we can try an [Ensemble Learning](https://en.wikipedia.org/wiki/Ensemble_learning) method such as [Gradient-Boosted Decision Trees](https://en.wikipedia.org/wiki/Gradient_boosting) to see if we can strengthen our model by using an ensemble of weaker trees with weighting to reduce the error in our model.

[Random forests](https://en.wikipedia.org/wiki/Random_forest) or random decision tree forests are an ensemble learning method for regression that operate by constructing a multitude of decision trees at training time and outputting the class that is the mean prediction (regression) of the individual trees. Random decision forests correct for decision trees' habit of overfitting to their training set.

Spark ML Pipeline provides [RandomForestRegressor()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.RandomForestRegressor) as an implementation of [Random forests](https://en.wikipedia.org/wiki/Random_forest).

The cell below is based on the [Spark ML Pipeline API for Random Forest Regressor](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.RandomForestRegressor).

### Exercise 7(f)

- Read the [Random Forest Regressor](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.RandomForestRegressor) documentation
- In the next cell, create a [RandomForestRegressor()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.RandomForestRegressor)
- The next step is to set the parameters for the method (we do this for you):
  - Set the name of the prediction column to "Prediction_PE"
  - Set the name of the label column to "PE"
  - Set the name of the features column to "features"
  - Set the random number generator seed to 190088121
  - Set the maximum depth to 8
  - Set the number of trees to 25
- Create the [ML Pipeline](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.Pipeline) and set the stages to the Vectorizer we created earlier and [RandomForestRegressor()](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.regression.RandomForestRegressor) learner we just created.

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code.

from pyspark.ml.regression import RandomForestRegressor

# Create a RandomForestRegressor
rf = RandomForestRegressor()

rf.setLabelCol("PE")\
  .setPredictionCol("Prediction_PE")\
  .setFeaturesCol("features")\
  .setSeed(190088121)\
  .setMaxDepth(8)\
  .setNumTrees(25)

# Create a Pipeline
rfPipeline = Pipeline()

# Set the stages of the Pipeline
rfPipeline.setStages([vectorizer,rf])


Out[40]: Pipeline_5545d16c8954

In [0]:
# TEST
Test.assertEqualsHashed(rfPipeline.getStages()[0].__class__.__name__, '4617be70bcf475326c0b07400b97b13457cc4949', "Stage 0 of pipeline is not correct")
Test.assertEqualsHashed(rfPipeline.getStages()[1].__class__.__name__, 'ecdcce2d075f00c97a6d2a2b8b1f66de322e57d2', "Stage 1 of pipeline is not correct")

1 test passed.
1 test passed.


As with Decision Trees, instead guessing what parameters to use, we will use [Model Selection](https://spark.apache.org/docs/1.6.2/ml-tuning.html#model-selection-aka-hyperparameter-tuning) or [Hyperparameter Tuning](https://spark.apache.org/docs/1.6.2/ml-tuning.html#model-selection-aka-hyperparameter-tuning) to create the best model.

We can reuse the exiting [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) by replacing the Estimator with our new `rfPipeline` (the number of folds remains 3).

### Exercise 7(g)

- Use [ParamGridBuilder](https://spark.apache.org/docs/1.6.2/api/python/pyspark.ml.html#pyspark.ml.tuning.ParamGridBuilder) to build a parameter grid with the parameter `rf.maxBins` and a list of the values 50 and 100, and add the grid to the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation)
- Run the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) to find the parameters that yield the best model (i.e., lowest RMSE) and return the best model.

_Note that it will take some time to run the [CrossValidator](https://spark.apache.org/docs/1.6.2/ml-tuning.html#cross-validation) as it will run almost 100 Spark jobs, and each job takes longer to run than the prior CrossValidator runs._

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code.
# Let's just reuse our CrossValidator with the new rfPipeline,  RegressionEvaluator regEval, and 3 fold cross validation
crossval.setEstimator(rfPipeline)

# Let's tune over our rf.maxBins parameter on the values 50 and 100, create a paramter grid using the ParamGridBuilder
paramGrid = (ParamGridBuilder()
             .addGrid(rf.maxBins,(50,100))
             .build())

# Add the grid to the CrossValidator
crossval.setEstimatorParamMaps(paramGrid)

# Now let's find and return the best model
rfModel = crossval.fit(trainingSetDF).bestModel

In [0]:
# TEST
Test.assertEqualsHashed(rfModel.stages[0].__class__, 'f0c3b910468d87808e019409e7ae5e587d6aca3d', 'rfModel has incorrect stage 0')
Test.assertEqualsHashed(rfModel.stages[1].__class__, '0ed43512ea7e35ebeebeed3ddac0186248999a87', 'rfModel has incorrect stage 1')

1 test passed.
1 test passed.


### Exercise 7(h)

Now let's see how our tuned RandomForestRegressor model's RMSE and \\(r^2\\) values compare to our tuned LinearRegression and tuned DecisionTreeRegressor models.

** TODO**: Complete and run the next cell.

In [0]:
# TODO: Replace <FILL_IN> with the appropriate code.

# Now let's use rfModel to compute an evaluation metric for our test dataset: testSetDF
resultsDF = rfModel.transform(testSetDF)

# Run the previously created RMSE evaluator, regEval, on the resultsDF DataFrame
rmseRF = regEval.evaluate(resultsDF)

# Now let's compute the r2 evaluation metric for our test dataset
r2RF = regEval.evaluate(resultsDF, {regEval.metricName: "r2"})

print("LR Root Mean Squared Error: {0:.2f}".format(rmseNew))
print("DT Root Mean Squared Error: {0:.2f}".format(rmseDT))
print("RF Root Mean Squared Error: {0:.2f}".format(rmseRF))
print("LR r2: {0:.2f}".format(r2New))
print("DT r2: {0:.2f}".format(r2DT))
print("RF r2: {0:.2f}".format(r2RF))

LR Root Mean Squared Error: 4.55
DT Root Mean Squared Error: 5.07
RF Root Mean Squared Error: 3.49
LR r2: 0.93
DT r2: 0.91
RF r2: 0.96


In [0]:
# TEST
Test.assertEquals(round(rmseRF, 2), 3.49, "Incorrect value for rmseRF")
Test.assertEquals(round(r2RF, 2), 0.96, "Incorrect value for r2RF")

1 test passed.
1 test passed.


Note that the RMSE for the Random Forest model is better.

The line below will pull the Random Forest model from the Pipeline as display it as an if-then-else string.

**ToDo**: Run the next cell

In [0]:
print(rfModel.stages[-1]._java_obj.toDebugString())

RandomForestRegressionModel: uid=RandomForestRegressor_dfd924cc305e, numTrees=25, numFeatures=4
  Tree 0 (weight 1.0):
    If (feature 0 <= 17.805)
     If (feature 2 <= 1018.625)
      If (feature 1 <= 44.885000000000005)
       If (feature 1 <= 40.504999999999995)
        If (feature 3 <= 83.365)
         If (feature 0 <= 12.44)
          If (feature 3 <= 52.650000000000006)
           If (feature 2 <= 1015.545)
            Predict: 489.59
           Else (feature 2 > 1015.545)
            Predict: 488.7194444444445
          Else (feature 3 > 52.650000000000006)
           If (feature 2 <= 1010.725)
            Predict: 477.8168817204301
           Else (feature 2 > 1010.725)
            Predict: 480.0659117997617
         Else (feature 0 > 12.44)
          If (feature 1 <= 40.224999999999994)
           If (feature 0 <= 15.114999999999998)
            Predict: 468.8871064467766
           Else (feature 0 > 15.114999999999998)
            Predict: 463.57565420560735
          Else (

### Conclusion

Wow! So our best model is in fact our Random Forest tree model which uses an ensemble of 25 Trees with a depth of 8 to construct a better model than the single decision tree.